USE hb_news;
INSERT INTO users (name, surname, email, password, imagenUrl, biography, active) 
VALUES 
('Eduardo', 'Castro Bianch', 'eduardo@gmail.com', SHA2('123456',512), 'https://i.pinimg.com/170x/b9/9a/30/b99a309f679ff9154edc78d8db0575ea.jpg', 'Soy desarollador web', true),
('Guillermo', 'De La Rosa', 'guillermo@gmail.com', SHA2('123456',512), 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSDv22Pa8W1Tmf2uOYMLV-JuG1mMA6K8ezZg&usqp=CAU', 'Soy desarollador web', true),
('Fran', 'Valderrey', 'fran@gmail.com', SHA2('123456',512), 'https://c.wallhere.com/photos/74/7a/V_for_Vendetta_mask_Guy_Fawkes_mask-76525.jpg!d', 'Soy desarollador web', true),
('David', 'Martinez Quiroga', 'david@gmail.com', SHA2('123456',512), 'https://images.fineartamerica.com/images/artworkimages/medium/2/calimero-show-vesna-antic.jpg', 'Soy desarollador web', true);



INSERT INTO category (name) 
VALUES 
('Actualidad'),
('Sanidad'),
('Naturaleza'),
('Ciencia y tecnología'),
('Economía y negocios'),
('Deportes'),
('Entretenimiento'),
('Psicología'),
('Estilo de vida');



INSERT INTO news (userId, imagenUrl, title, publishDate, score, fakeNews, categoryId, introText, text)
VALUES
    (4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlCRHIiN6pewCQVR7eXtpZsIysJb-MK9RTHeIBS_tw-NK-Qovv5feiqOJFLK3ZjDhqdhc&usqp=CAU', 'Descubrimientos revolucionarios!!!', NOW(), 20, 0, 4, 'Descubrimientos revolucionarios en la Ciencia y Tecnología', 'El descubrimiento se basa en años de investigación intensiva y colaboración entre científicos de todo el mundo. Mediante el uso de tecnologías de vanguardia, los investigadores han logrado desarrollar un nuevo material con propiedades nunca antes vistas. Este material tiene el potencial de revolucionar diversas industrias, desde la medicina hasta la energía renovable. Además, sus características únicas podrían permitir avances significativos en áreas como la electrónica, la informática cuántica y la nanotecnología. Los expertos predicen que este descubrimiento marcará un hito en la historia de la ciencia y abrirá nuevas puertas hacia un futuro lleno de posibilidades innovadoras.'),
    (4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV4Xjkb4Ax0T-VoOtXjCNVqzrf3cdgEzp9jg&usqp=CAU', 'Descubren nuevo planeta habitable en sistema solar cercano', NOW(), 20, 53, 4, 'Científicos han hecho un emocionante hallazgo!!', 'En un descubrimiento sin precedentes, astrónomos han identificado un nuevo planeta en un sistema solar cercano que presenta condiciones propicias para la existencia de vida. El exoplaneta, llamado Kepler-452b, se encuentra en la "zona habitable" alrededor de su estrella, lo que sugiere la posibilidad de que albergue agua líquida y sea adecuado para la vida tal como la conocemos. Este hallazgo plantea nuevas interrogantes sobre la existencia de otros mundos habitables y el potencial de encontrar formas de vida extraterrestre.'),
    (4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdWj9Q-QZ7ELR-saD5N-3vMM4RTifboJABFA&usqp=CAU', 'Descubren vínculo entre la psicología y la salud física', '2022-06-16 00:23:10', 15, 0, 8, 'Interesante estudio en la categoría de Psicología.', 'Un nuevo estudio ha revelado una estrecha conexión entre la psicología y la salud física. Los investigadores encontraron que el bienestar mental y emocional de una persona puede tener un impacto significativo en su estado de salud general. Factores como el estrés, la ansiedad y la depresión pueden aumentar el riesgo de desarrollar enfermedades crónicas y disminuir la calidad de vida. Este descubrimiento resalta la importancia de abordar tanto la salud mental como la física para lograr un bienestar integral.'),
    (4, 'https://i.ytimg.com/vi/ikQ6C5JL_7U/maxresdefault.jpg', 'Estreno de película taquillera', NOW(), 22, 0, 7, 'Emocionante estreno', 'La esperada película ha llegado a los cines y ha cautivado al público de todo el mundo. Con efectos especiales impresionantes, una trama emocionante y actuaciones destacadas, esta película promete ser uno de los éxitos de taquilla del año. Los fanáticos han elogiado la calidad cinematográfica y están ansiosos por ver las próximas entregas de la saga. Sin duda, este estreno ha generado gran entusiasmo y expectativas en el mundo del entretenimiento.'),
    (4, 'https://p.calameoassets.com/170927192642-fe899917ca9e3dd8ffde1219f281f668/p1.jpg', 'Investigadores descubren nuevos avances en el campo de la psicología', NOW(), 28, 0, 8, 'Importantes avances en el campo de la Psicología.', 'Un equipo de investigadores ha logrado importantes avances en el campo de la psicología con su último estudio. Mediante la utilización de nuevas técnicas de investigación y la aplicación de teorías innovadoras, han obtenido resultados prometedores que podrían tener un impacto significativo en el tratamiento de trastornos mentales y el bienestar emocional. Estos hallazgos abren nuevas perspectivas para la psicología y brindan esperanza a aquellos que luchan con problemas de salud mental.'),
    (4, 'https://img2.rtve.es/i/?w=1600&i=1634504721681.jpg', 'Estrella de cine aclamada recibe premio a la trayectoria', NOW(), 19, 0, 7, 'Reconocimiento a una estrella de cine', 'Una de las estrellas más queridas de la industria del cine ha sido honrada con un premio a su destacada trayectoria. Esta reconocida actriz ha cautivado a audiencias de todo el mundo con sus interpretaciones memorables y su talento excepcional. Su contribución a la industria del entretenimiento ha sido invaluable y su legado perdurará en la historia del cine. Este premio es un merecido reconocimiento a su dedicación y talento.'),
    (4, 'https://que-es.online/wp-content/uploads/2023/04/avances-tecnologicos-en-la-robotica.jpg', 'Avances tecnológicos revolucionan la industria', NOW(), 24, 0, 4, 'Innovación tecnológica', 'Los avances tecnológicos continúan transformando diversas industrias, desde la medicina hasta la comunicación. Investigadores y empresas han desarrollado nuevas soluciones y dispositivos que mejoran la calidad de vida de las personas y optimizan los procesos en diferentes sectores. Estos avances revolucionarios prometen abrir nuevas oportunidades y desafíos en un mundo cada vez más digitalizado y conectado.'),
    (4, 'https://www.laespanolaaceites.com/wp-content/uploads/2016/08/LE-Blog-aros-olimpicos-750x450-1.jpg', 'Juegos Olímpicos', NOW(), 16, 0, 6, 'Preparativos para los Juegos Olímpicos', 'El equipo nacional ha comenzado su preparación para los próximos Juegos Olímpicos. Los atletas están entrenando arduamente y mostrando un gran compromiso para representar a su país en la competencia internacional más importante. Los deportistas están decididos a alcanzar su máximo rendimiento y llevar a casa medallas para su nación. Esta etapa de preparativos es crucial y genera una gran expectativa en los aficionados y seguidores del deporte.') ,
    (4, 'https://images.ecestaticos.com/X4OSUYgdaxhq8flZf3g1XWxJDCU=/0x0:1174x893/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Facf%2F4a7%2F72c%2Facf4a772cb60541c5da9988ab6a84e19.jpg', 'Descubren nueva especie de dinosaurio', NOW(), 18, 0, 3, 'Fascinante hallazgo!', 'Científicos han anunciado el descubrimiento de una nueva especie de dinosaurio, que ha sido denominada "Diplodocus magnificus". Los fósiles encontrados revelan características únicas de esta criatura prehistórica, brindando nuevas perspectivas sobre la evolución y la diversidad de los dinosaurios. Este hallazgo emocionante proporciona información valiosa para comprender mejor el pasado de nuestro planeta.'),
    (4, 'https://plustatic.com/7389/meditacion-chakra.jpg', 'Estudio revela los beneficios de la meditación', '2022-06-16 00:23:10', 16, 0, 9, 'Descubrimientos sobre la meditación y su efecto en dla Salud y Bienestar.', 'Un estudio reciente ha demostrado los numerosos beneficios de la meditación para la salud y el bienestar. Los investigadores encontraron que la práctica regular de la meditación puede reducir el estrés, mejorar la concentración y promover un estado de calma mental. Además, se observaron efectos positivos en la salud física, como la disminución de la presión arterial y la mejora del sistema inmunológico. Estos resultados respaldan la importancia de incorporar la meditación en la rutina diaria para mantener un equilibrio integral.'),
    (4, 'https://cdn-icons-png.flaticon.com/512/26/26805.png', 'Lanzamiento de nuevo álbum de música!', NOW(), 22, 0, 7, 'The show must go on!', 'El aclamado artista ha lanzado su nuevo álbum, que ha generado gran expectativa entre sus seguidores. Con canciones que exploran diversos géneros musicales y letras profundas, este trabajo promete cautivar a los amantes de la música. El artista ha compartido que este álbum representa una nueva etapa en su carrera y refleja su evolución artística. Los fanáticos están ansiosos por disfrutar de estas nuevas composiciones y descubrir las sorpresas que les esperan.'),
    (4, 'https://www.fayerwayer.com/resizer/_OT5B1UXhJa7GoaYh2D0PqopSt0=/800x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/VCBEMF3DTNAORJ2EG3YSDQLQT4.jpg', 'Investigadores descubren posible cura para una enfermedad', NOW(), 25, 4, 2, 'Avances médicos en Suiza', 'Un grupo de investigadores ha anunciado un importante avance en la búsqueda de una cura para una enfermedad hasta ahora incurable. Mediante innovadoras terapias génicas, los científicos han logrado revertir los efectos de esta enfermedad en modelos de laboratorio, abriendo nuevas posibilidades para su tratamiento en humanos. Este descubrimiento ofrece esperanza a los pacientes y destaca el potencial de la medicina genética en el combate contra enfermedades difíciles de tratar.'),
    (4, 'https://www.entrevistadetrabajo.org/wp-content/uploads/2016/07/entrevista-de-trabajo-para-deportista-de-elite-1280x720.jpg', 'Atletas de élite', NOW(), 19, 0, 6, 'Evento deportivo internacional reúne a super deportistas', 'Un evento deportivo de renombre internacional está en marcha, convocando a los mejores atletas de todo el mundo. En esta competencia de alto nivel, los deportistas están demostrando su destreza y habilidades en disciplinas variadas, desde natación y atletismo hasta gimnasia y tenis. Los fanáticos del deporte están siguiendo de cerca las emocionantes actuaciones y disfrutando de un espectáculo deportivo de primer nivel.'),
    (4, 'https://cdn-3.expansion.mx/dims4/default/36fa49f/2147483647/strip/true/crop/683x512+0+0/resize/1200x900!/format/webp/quality/60/?url=https%3A%2F%2Fcdn-3.expansion.mx%2F3d%2F3df09b7629e141448b11b1787bf8ebc9%2Fimpresin-3d-automvil.jpg', 'Nuevas tecnologías revolucionan la industria automotriz', NOW(), 21, 0, 4, 'Avances tecnologicos muy interesates', 'La industria automotriz está experimentando una revolución gracias a las nuevas tecnologías. Desde vehículos eléctricos hasta sistemas de conducción autónoma, los avances están transformando la forma en que nos desplazamos. Estas innovaciones no solo tienen el potencial de reducir la huella ambiental, sino también de mejorar la seguridad vial y la experiencia de conducción. Los fabricantes de automóviles están trabajando arduamente para implementar estas tecnologías y dar forma al futuro del transporte.'),
    (4, 'https://www.caracteristicas.pro/wp-content/uploads/2023/01/arte-contemporaneo.jpg', 'Exposición de arte contemporáneo destaca talento local', NOW(), 17, 0, 1, 'Evento artístico', 'Una destacada exposición de arte contemporáneo está presentando obras de talentosos artistas locales. Esta muestra diversa y creativa representa una amplia gama de estilos y expresiones artísticas. Los visitantes tienen la oportunidad de apreciar el arte en todas sus formas, desde pinturas y esculturas hasta instalaciones y arte digital. Este evento cultural destaca la importancia del arte en nuestra sociedad y celebra el talento de los artistas de la región.') ,
	(4, 'https://radionacional-v3.s3.amazonaws.com/s3fs-public/styles/amp_1200x900_4_3/public/node/article/field_image/WhatsApp%20Image%202022-01-13%20at%206.06.06%20PM%20%281%29.jpeg?itok=GfmmR0C9', 'Descubrimiento arqueológico revela antiguas civilizaciones', NOW(), 23, 0, 1, 'Hallazgo arqueológico asombroso', 'Arqueólogos han hecho un emocionante descubrimiento en una remota región, revelando evidencias de antiguas civilizaciones que existieron hace miles de años. Los hallazgos incluyen ruinas, artefactos y pinturas rupestres que ofrecen nuevas perspectivas sobre la historia y la cultura de estos pueblos perdidos. Este descubrimiento arqueológico es un hito importante en la comprensión de nuestro pasado y despierta el interés de investigadores de todo el mundo.'),
	(4, 'https://adelaweb.org/wp-content/uploads/2016/04/aprobada-la-primera-estrategia-para-enfermedades-neurodegenerativas.png', 'Nueva terapia prometedora para enfermedades neurodegenerativas', NOW(), 26, 0, 2, 'Avances médicos en neurología', 'Científicos han desarrollado una terapia experimental que muestra resultados prometedores en el tratamiento de enfermedades neurodegenerativas, como el Alzheimer y el Parkinson. Esta terapia utiliza enfoques innovadores para estimular la regeneración neuronal y proteger las células cerebrales del daño. Los estudios preclínicos han demostrado una mejoría significativa en los síntomas y la calidad de vida de los pacientes. Este avance representa una luz de esperanza en la lucha contra estas enfermedades debilitantes.'),
	(4, 'https://www.turismofinlandia.es/wp-content/uploads/2018/02/ruisrock-turku-finlandia-1024x681.jpg', 'Festival de música internacional atrae a multitudes', NOW(), 18, 0, 7, 'Gran evento musical', 'El festival de música más esperado del año está en pleno apogeo, atrayendo a multitudes de amantes de la música de todas partes. Con un cartel de artistas de renombre mundial y una atmósfera vibrante, este evento se ha convertido en un ícono de la escena musical internacional. Los asistentes están disfrutando de actuaciones en vivo inolvidables y compartiendo experiencias musicales únicas. Este festival es una celebración de la diversidad musical y un escaparate para talentos emergentes.'),
	(4, 'https://imagenes.iberoeconomia.es/wp-content/uploads/2022/07/02233150/cambio-climatico-que-es-definicion-causas-efectos-consecuencias-y-combate-1.jpg', 'Avances en la lucha contra el cambio climático', NOW(), 24, 5, 3, 'Iniciativas para combatir el cambio climático', 'El mundo está tomando medidas concretas para combatir el cambio climático y reducir las emisiones de gases de efecto invernadero. Desde acuerdos internacionales hasta inversiones en energías renovables y proyectos de conservación, se están implementando estrategias para mitigar los impactos del calentamiento global. Estos esfuerzos reflejan la creciente conciencia sobre la importancia de proteger nuestro planeta y garantizar un futuro sostenible para las generaciones venideras.'),
	(4, 'https://elbocon.pe/resizer/46NWuKuiQvZFEMau1zkPpI3PZb4=/580x330/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/I4JRMS7XLFDFJC72FXVJTYIWTA.jpg', 'Récord mundial en competencia deportiva', '2022-06-16 00:23:10', 19, 0, 6, 'Logro histórico en el deporte', 'Un atleta ha logrado establecer un nuevo récord mundial en una competencia deportiva de alto nivel. Con una actuación sobresaliente y una dedicación excepcional, ha superado las marcas anteriores y dejado una huella imborrable en la historia del deporte. Este logro destaca la importancia del entrenamiento, la perseverancia y el espíritu competitivo en la búsqueda de la excelencia.'),
	(4, 'https://upload.wikimedia.org/wikipedia/commons/9/98/EdWhiteFirstAmericanSpacewalker.1965.ws.jpg', 'Descubrimiento en el espacio revela secretos del universo', '2022-06-16 00:23:10', 27, 0, 4, 'Asombroso descubrimiento astronómico', 'Astrónomos han realizado un descubrimiento sorprendente que arroja luz sobre los misterios del universo. Mediante el uso de telescopios avanzados, han identificado nuevas galaxias distantes y estudiado fenómenos cósmicos extraordinarios. Estos hallazgos ayudan a expandir nuestro conocimiento sobre el cosmos y plantean nuevas preguntas sobre la naturaleza del universo.'),
	(4, 'https://imagenes.lainformacion.com/files/image_656_370/uploads/imagenes/2019/11/05/59c5b822a9bcf.jpeg', 'Premios reconocen el talento en la industria del cine', NOW(), 20, 0, 7, 'Gala de premios cinematográficos', 'La industria del cine ha celebrado una gala de premios en la que se reconoció el talento y la excelencia en el séptimo arte. Actores, directores, guionistas y otros profesionales del cine fueron honrados por sus contribuciones sobresalientes. Esta ceremonia resalta la importancia del cine como forma de expresión artística y celebra los logros de los cineastas de todo el mundo.'),
	(1, 'https://img.youtube.com/vi/09kyKcr3Lyw/0.jpg', 'Nuevas investigaciones arrojan luz sobre la historia antigua', NOW(), 23, 13, 1, 'Descubrimientos históricos fascinantes', 'Investigadores han realizado descubrimientos arqueológicos que ofrecen nuevas perspectivas sobre la historia antigua. Ruinas, artefactos y textos recién descubiertos han revelado detalles intrigantes sobre civilizaciones olvidadas y eventos históricos significativos. Estos hallazgos arrojan luz sobre nuestro pasado y nos ayudan a comprender mejor el desarrollo de la humanidad.'),
	(1, 'https://estaticos-cdn.elperiodico.com/clip/57fe7f78-5f7a-460e-b3b1-c4b96e5200d2_alta-libre-aspect-ratio_default_0.jpg', 'Estudio científico desafía teoría aceptada', '2022-06-16 00:23:10', 17, 0, 4, 'Investigación controvertida', 'Un estudio científico reciente ha desafiado una teoría ampliamente aceptada en el campo de la ciencia. Los resultados de esta investigación cuestionan las ideas establecidas y plantean nuevas hipótesis sobre el funcionamiento de fenómenos naturales. Esta controversia científica genera debates y estimula la investigación adicional para explorar y comprender mejor el mundo que nos rodea.'),
	(1, 'https://netmd.org/images/laboratorio.jpg', 'Nuevas terapias prometedoras para el tratamiento del cáncer', NOW(), 25, 0, 2, 'Avances médicos en oncología', 'Investigadores han desarrollado terapias innovadoras que muestran promesa en el tratamiento del cáncer. Estas terapias incluyen enfoques como la inmunoterapia, la terapia génica y la medicina de precisión, y ofrecen nuevas esperanzas a los pacientes con cáncer. Los estudios clínicos preliminares han demostrado resultados alentadores y han abierto nuevas puertas para combatir esta enfermedad devastadora.'),
	(1, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcUaS3PwMxhJUvx0r1jCSkx8zZGOrs6dN54Csl9-Zx8W7S71_NSJnz4UrMzFSUQSVhDQ0&usqp=CAU', 'Artista emergente sorprende con su talento', '2022-06-16 00:23:10', 18, 1, 7, 'Descubrimiento en el mundo del arte', 'Un artista emergente ha llamado la atención del mundo del arte con su talento y originalidad. Sus obras expresivas y únicas han cautivado a críticos y amantes del arte, y se han convertido en objeto de admiración y colección. Este artista representa una nueva voz en el panorama artístico y promete seguir sorprendiendo con su creatividad.'),
	(1, 'https://mott.pe/noticias/wp-content/uploads/2017/10/los-mejores-lugares-para-estudiar-cursos-de-dise%C3%B1o-de-modas-en-lima.jpg', 'Avances tecnológicos revolucionan la industria de la moda', NOW(), 22, 0, 5, 'Moda del futuro', 'La industria de la moda está experimentando una transformación gracias a los avances tecnológicos. La integración de la inteligencia artificial, la realidad aumentada y los textiles inteligentes está cambiando la forma en que diseñamos, fabricamos y experimentamos la moda. Estas innovaciones prometen mejorar la sostenibilidad, la personalización y la accesibilidad en el mundo de la moda.'),
	(1, 'https://www.mysteryscience.net/wp-content/uploads/2019/05/atlantida-dibujo-ciudad-perdida-2.jpg', 'Descubrimiento arqueológico revela civilización perdida', '2022-06-16 00:23:10', 26, 0, 1, 'Hallazgo arqueológico extraordinario', 'Arqueólogos han hecho un descubrimiento sin precedentes que revela una civilización perdida en una región remota. Los vestigios arqueológicos encontrados proporcionan información valiosa sobre esta antigua sociedad y su forma de vida. Este hallazgo arqueológico arroja luz sobre la historia humana y abre nuevas perspectivas para investigaciones futuras.'),
	(1, 'https://ceupe.com.ar/blog/wp-content/uploads/2021/05/01-42.jpg', 'Investigadores desarrollan tecnología revolucionaria en energía renovable', '2022-06-16 00:23:10', 24, 0, 4, 'Energía del futuro', 'Un equipo de investigadores ha logrado un avance significativo en el campo de la energía renovable con el desarrollo de una tecnología revolucionaria. Esta innovación permite la generación de energía limpia de manera más eficiente y sostenible, abriendo nuevas posibilidades para reducir nuestra dependencia de los combustibles fósiles y mitigar el cambio climático.'),
	(2, 'https://escueladeexperiencias.com/wp-content/uploads/2017/09/neurociencia.png', 'Descubrimientos en neurociencia desafían nuestra comprensión del cerebro', NOW(), 20, 0, 2, 'Nuevos hallazgos en neurociencia', 'Investigadores en el campo de la neurociencia han realizado descubrimientos sorprendentes que desafían nuestra comprensión actual del cerebro humano. Estos hallazgos revelan nuevas conexiones neuronales, procesos cognitivos inesperados y mecanismos de plasticidad cerebral. Esta investigación promete expandir nuestro conocimiento sobre el cerebro y tener implicaciones en el tratamiento de enfermedades neurológicas y trastornos mentales.'),
	(2, 'https://fundaciondelcorazon.com/images/ejercicio/ejercicio.jpg', 'Nuevo estudio demuestra los beneficios del ejercicio regular', NOW(), 18, 0, 9, 'Ejercicio y bienestar', 'Un estudio científico reciente ha confirmado los numerosos beneficios del ejercicio regular para la salud y el bienestar. Se encontró que la actividad física regular no solo mejora la condición física, sino que también reduce el riesgo de enfermedades crónicas, mejora el estado de ánimo y aumenta la longevidad. Estos hallazgos refuerzan la importancia de mantener un estilo de vida activo y saludable.'),
	(2, 'https://wp.catedu.es/aula4apedrojrubio/wp-content/uploads/sites/37/2018/02/CHAPLIN-5.jpg', 'Festival de cine independiente celebra la creatividad y la diversidad', NOW(), 21, 0, 7, 'Celebración del cine independiente', 'Un festival de cine independiente ha reunido a cineastas y amantes del cine para celebrar la creatividad y la diversidad en la industria cinematográfica. Esta plataforma ofrece un espacio para películas independientes y alternativas que exploran nuevos géneros, temas y estilos. El festival destaca el poder del cine como medio de expresión artística y fomenta el diálogo y el intercambio cultural.'),
	(2, 'https://img.europapress.es/fotoweb/fotonoticia_20160714074433_420.jpg', 'Investigación revela nuevos datos sobre la evolución humana', NOW(), 26, 10, 4, 'Descubrimiento en paleoantropología', 'Una investigación en el campo de la paleoantropología ha revelado nuevos datos sobre la evolución humana y nuestros antepasados. Mediante el análisis de fósiles y el estudio de ADN antiguo, los científicos han trazado conexiones entre diferentes especies y descubierto características únicas de nuestra historia evolutiva. Estos hallazgos arrojan luz sobre los orígenes y el desarrollo de la humanidad.'),
	(2, 'https://img.freepik.com/fotos-premium/telefono-celular-futuro-transparente-invisible-movil-siri-alice-holograma-inteligencia-artificial-telefono-inteligente-ai-metaverse-blockchain-technology-innovadora-red-datos-futuros_771426-7289.jpg', 'Nueva empresa de tecnología lanza innovador dispositivo móvil', NOW(), 19, 0, 5, 'Tecnología disruptiva', 'Una nueva empresa de tecnología ha lanzado un dispositivo móvil innovador que promete cambiar la forma en que interactuamos con la tecnología. Con características y capacidades revolucionarias, este dispositivo redefine la experiencia móvil y ofrece nuevas posibilidades en términos de comunicación, entretenimiento y productividad. Esta innovación refleja el constante avance y la evolución de la tecnología móvil.'),
	(2, 'https://lanoticia.com/wp-content/uploads/2021/05/astronomia.jpeg', 'Descubrimientos en astronomía desvelan secretos del universo', '2022-06-16 00:23:10', 23, 0, 4, 'Explorando el cosmos', 'Avances en la astronomía han permitido hacer descubrimientos fascinantes sobre el universo. Nuevos telescopios y observatorios espaciales han revelado fenómenos cósmicos intrigantes, como agujeros negros, planetas extrasolares y señales de vida en otros lugares del universo. Estos hallazgos nos acercan a comprender la vastedad y la complejidad del cosmos.'),
	(2, 'https://www.doctorponce.com/wp-content/uploads/2017/03/medicina-pasada-de-moda-actual-pendiente-doctor-ponce.png', 'Nuevas investigaciones en medicina prometen tratamientos más efectivos', NOW(), 27, 0, 2, 'Avances médicos prometedores', 'La investigación médica está abriendo nuevas vías para el tratamiento de enfermedades y condiciones médicas. Desde terapias génicas hasta medicina regenerativa y nanomedicina, los avances en medicina prometen tratamientos más efectivos y personalizados. Estos descubrimientos tienen el potencial de mejorar la calidad de vida de millones de personas en todo el mundo.'),
	(3, 'https://www.latercera.com/resizer/vPTWgoQicvZQn7t2h-Byca8l0i4=/900x600/smart/cloudfront-us-east-1.images.arcpublishing.com/copesa/MCB47V36PVFVLLJXB7AEMYULYI.jpg', 'Avances en inteligencia artificial revolucionan diferentes industrias', NOW(), 25, 0, 5, 'La era de la inteligencia artificial', 'La inteligencia artificial está transformando diferentes sectores industriales, desde la atención médica y la automoción hasta el comercio electrónico y la seguridad. Los algoritmos inteligentes y el aprendizaje automático están impulsando la eficiencia, la personalización y la automatización en múltiples procesos. Estos avances tienen el potencial de cambiar la forma en que vivimos y trabajamos.'),
	(3, 'https://factoriaestudio.es/wp-content/uploads/Banksy-600x450.jpg', 'Artista contemporáneo desafía las convenciones del arte', NOW(), 21, 0, 7, 'Rompiendo barreras artísticas', 'Un artista contemporáneo está desafiando las convenciones del arte con su enfoque innovador y provocador. Sus obras despiertan controversia y cuestionan las normas establecidas, llevando el arte a nuevos territorios emocionales y conceptuales. Este artista desafía las barreras y nos invita a reflexionar sobre el significado y el propósito del arte en la sociedad actual.'),
	(3, 'https://ml8ebsxqrqhi.i.optimole.com/w:1024/h:512/q:mauto/f:avif/https://www.escolaart.com/wp-content/uploads/2022/08/Piramides-de-Gizah.jpg', 'Nuevo descubrimiento arqueológico en Egipto', '2022-06-16 00:23:10', 20, 0, 1, 'Hallazgo asombroso en la categoría de Actualidad', 'Arqueólogos han realizado un descubrimiento emocionante en Egipto, desenterrando una antigua tumba que data de miles de años atrás. El hallazgo revela valiosos artefactos y pinturas murales que proporcionan información fascinante sobre la historia y la cultura de la civilización antigua. Este descubrimiento arqueológico ha generado gran entusiasmo en la comunidad científica y promete arrojar nueva luz sobre el pasado de esta región.'),
	(3, 'https://www.consalud.es/uploads/s1/16/68/08/0/colaboracion-en-la-investigacion-del-cancer-y-covid-foto-real-academia-europea-de-doctores.jpeg', 'Avances en la investigación del cáncer', NOW(), 20, 0, 2, 'Descubrimientos prometedores en la categoría de Sanidad', 'Científicos han logrado importantes avances en la investigación del cáncer, identificando nuevas terapias y enfoques para combatir esta enfermedad devastadora. Estos hallazgos ofrecen esperanza a los pacientes y sus familias, abriendo la puerta a tratamientos más efectivos y personalizados. La comunidad médica está entusiasmada con estos descubrimientos y trabaja arduamente para traducirlos en opciones de tratamiento viables.'),
	(3, 'https://www.lostiempos.com/sites/default/files/styles/noticia_detalle/public/media_imagen/2023/4/19/medusa.jpg?itok=AfE1qniH', 'Descubrimiento de una nueva especie marina', NOW(), 15, 0, 3, 'Emocionante hallazgo en la categoría de Naturaleza', 'Científicos han anunciado el descubrimiento de una nueva especie marina en las profundidades del océano. Esta criatura desconocida hasta ahora presenta características únicas y representa un importante hallazgo para la biodiversidad marina. Los expertos destacan la importancia de proteger los ecosistemas oceánicos y continuar explorando las profundidades para descubrir nuevas formas de vida.'),
	(3, 'https://www.lavanguardia.com/files/article_main_microformat/uploads/2022/12/28/63ac575451ed4.jpeg', 'Descubrimiento arqueológico revela antiguas civilizaciones', '2022-06-16 00:23:10', 23, 0, 1, 'Hallazgo arqueológico asombroso', 'Arqueólogos han hecho un emocionante descubrimiento en una remota región, revelando evidencias de antiguas civilizaciones que existieron hace miles de años. Los hallazgos incluyen ruinas, artefactos y pinturas rupestres que ofrecen nuevas perspectivas sobre la historia y la cultura de estos pueblos perdidos. Este descubrimiento arqueológico es un hito importante en la comprensión de nuestro pasado y despierta el interés de investigadores de todo el mundo.'),
	(3, 'https://psigo.es/wp-content/uploads/2016/02/enfermedades-neurodegenerativas-psigo.jpg', 'Nueva terapia prometedora para enfermedades neurodegenerativas', NOW(), 26, 0, 2, 'Avances médicos en neurología', 'Científicos han desarrollado una terapia experimental que muestra resultados prometedores en el tratamiento de enfermedades neurodegenerativas, como el Alzheimer y el Parkinson. Esta terapia utiliza enfoques innovadores para estimular la regeneración neuronal y proteger las células cerebrales del daño. Los estudios preclínicos han demostrado una mejoría significativa en los síntomas y la calidad de vida de los pacientes. Este avance representa una luz de esperanza en la lucha contra estas enfermedades debilitantes.'),
	(3, 'https://www.artofdance.nl/wp-content/uploads/2019/07/Dominator-2019-27-390x390.jpg', 'Festival de música internacional atrae a multitudes', NOW(), 18, 0, 7, 'Gran evento musical', 'El festival de música más esperado del año está en pleno apogeo, atrayendo a multitudes de amantes de la música de todas partes. Con un cartel de artistas de renombre mundial y una atmósfera vibrante, este evento se ha convertido en un ícono de la escena musical internacional. Los asistentes están disfrutando de actuaciones en vivo inolvidables y compartiendo experiencias musicales únicas. Este festival es una celebración de la diversidad musical y un escaparate para talentos emergentes.'),
	(4, 'https://fotografias-compromiso.atresmedia.com/clipping/cmsimages02/2015/06/05/042B603A-574D-4085-A7B9-53BF8D0612B4/58.jpg', 'Avances en la lucha contra el cambio climático', NOW(), 24, 0, 3, 'Iniciativas para combatir el cambio climático', 'El mundo está tomando medidas concretas para combatir el cambio climático y reducir las emisiones de gases de efecto invernadero. Desde acuerdos internacionales hasta inversiones en energías renovables y proyectos de conservación, se están implementando estrategias para mitigar los impactos del calentamiento global. Estos esfuerzos reflejan la creciente conciencia sobre la importancia de proteger nuestro planeta y garantizar un futuro sostenible para las generaciones venideras.'),
	(4, 'https://www.lavozdegalicia.es/default/2022/03/09/00121646840451211852136/Foto/natacion.jpg', 'Récord mundial en natación', NOW(), 20, 0, 6, 'Logro deportivo impresionante', 'Un nadador talentoso ha establecido un nuevo récord mundial en una competencia internacional de natación. Su destacada actuación y su determinación incansable le han permitido superar marcas anteriores y dejar una huella en la historia del deporte. Este logro es un testimonio del arduo entrenamiento y la dedicación del atleta, así como de su habilidad para superar límites y desafiar las expectativas.'),
	(4, 'https://upload.wikimedia.org/wikipedia/commons/e/e4/River_RP.jpg', 'Descubren nuevas especies en selva tropical', NOW(), 19, 0, 3, 'Exploración en biodiversidad', 'Una expedición científica en una selva tropical ha descubierto varias especies nuevas para la ciencia, incluyendo plantas, insectos y animales. Estos hallazgos resaltan la importancia de conservar estos ecosistemas ricos en biodiversidad y promueven la investigación y el conocimiento sobre las especies que habitan en ellos. La expedición también ha revelado la existencia de hábitats únicos y frágiles que requieren protección para preservar la vida en la Tierra.'),
    (4, 'https://t2.uc.ltmcdn.com/es/posts/0/4/9/que_es_el_dia_mundial_del_medio_ambiente_y_como_celebrarlo_6940_orig.jpg', 'Nueva legislación para proteger el medio ambiente', '2022-06-16 00:23:10', 22, 0, 3, 'Compromiso con la sostenibilidad', 'Un nuevo conjunto de leyes ha sido aprobado para fortalecer la protección del medio ambiente y promover la sostenibilidad. Estas regulaciones abordan temas como la reducción de residuos, la conservación de los recursos naturales y la promoción de prácticas ambientalmente responsables en los sectores público y privado. Esta legislación marca un paso importante hacia un futuro más verde y respetuoso con el planeta.'),
	(4, 'https://i.pinimg.com/originals/2a/f9/c7/2af9c72e280860202398f72c50fa4b84.jpg', 'Descubren nueva especie de mariposa en selva amazónica', NOW(), 17, 0, 3, 'Maravillas de la naturaleza', 'Científicos han identificado una nueva especie de mariposa en la selva amazónica. Esta colorida mariposa posee patrones únicos en sus alas y ha sido catalogada como una especie endémica de la región. El descubrimiento destaca la importancia de preservar los ecosistemas naturales y la biodiversidad que albergan. Estos hallazgos ofrecen nuevas oportunidades para estudiar y comprender mejor la vida en la selva tropical.'),
	(4, 'https://static.vecteezy.com/system/resources/previews/004/493/181/original/hospital-building-for-healthcare-background-illustration-with-ambulance-car-doctor-patient-nurses-and-medical-clinic-exterior-free-vector.jpg', 'Inauguración de nuevo hospital regional', '2022-06-16 00:23:10', 25, 0, 2, 'Mejora en infraestructura sanitaria', 'Un nuevo hospital regional ha sido inaugurado, brindando servicios de atención médica de calidad a la comunidad. Equipado con tecnología de vanguardia y un equipo médico altamente capacitado, este centro de salud se convierte en un punto de referencia en la región. La apertura del hospital representa un paso importante hacia la mejora de la infraestructura sanitaria y el acceso a la atención médica en la zona.'),
	(4, 'https://www.prensalibre.com/wp-content/uploads/2019/05/shutterstock_316507238.jpg?quality=82&w=1024', 'Estudio revela beneficios para la salud de estar en contacto con la naturaleza', '2022-06-16 00:23:10', 28, 0, 3, 'Bienestar y naturaleza', 'Una investigación científica ha demostrado los numerosos beneficios que tiene pasar tiempo en la naturaleza para nuestra salud y bienestar. Estar en contacto con entornos naturales, como bosques o parques, se ha asociado con una reducción del estrés, mejora del estado de ánimo, aumento de la vitalidad y fortalecimiento del sistema inmunológico. Estos hallazgos subrayan la importancia de conectarnos con la naturaleza y fomentar un estilo de vida equilibrado.'),
	(4, 'https://laverdadnoticias.com/__export/1641497156542/sites/laverdad/img/2022/01/06/salud_cardiovascular.jpg_478486366.jpg', 'Nuevo tratamiento prometedor contra enfermedades cardiovasculares', '2022-06-16 00:23:10', 21, 0, 2, 'Avances en cardiología', 'Investigadores han desarrollado un nuevo tratamiento que muestra resultados prometedores en el manejo de enfermedades cardiovasculares, como la hipertensión y la enfermedad coronaria. Este enfoque terapéutico innovador utiliza tecnología de vanguardia para mejorar la función cardíaca y reducir los riesgos asociados con estas enfermedades. Estos avances médicos ofrecen esperanza para aquellos que sufren de afecciones cardíacas y pueden tener un impacto significativo en la salud cardiovascular de la población.'),
	(4, 'https://www.iberdrola.com/documents/20125/40867/Bosques_746x419_01.jpg/f5514388-45f3-fe65-f03a-3ce0b8db9290?t=1627887728969', 'Descubren nueva reserva natural en área protegida', '2022-06-16 00:23:10', 18, 0, 3, 'Conservación de hábitats', 'Se ha descubierto una nueva reserva natural dentro de un área protegida, ampliando la extensión de hábitats preservados para diversas especies. Esta adición fortalece los esfuerzos de conservación y brinda más oportunidades para la investigación científica y el turismo ecológico. El descubrimiento destaca la importancia de proteger y preservar los ecosistemas naturales para garantizar la supervivencia de la vida silvestre y mantener la biodiversidad.'),
    (4, 'https://images.theconversation.com/files/506542/original/file-20230126-3492-aeig3w.png?ixlib=rb-1.1.0&q=45&auto=format&w=1000&fit=clip', 'Crece el comercio electrónico en el mercado global', NOW(), 26, 0, 5, 'Transformación en los hábitos de consumo', 'El comercio electrónico continúa experimentando un crecimiento significativo en el mercado global. Cada vez más personas optan por realizar compras en línea debido a la comodidad, la variedad de productos y los precios competitivos. Este cambio en los hábitos de consumo está transformando la forma en que las empresas operan y se espera que el comercio electrónico siga en aumento en los próximos años.'),
	(4, 'https://img.etimg.com/thumb/msid-92963920,width-1200,height-900,imgsize-19590,resizemode-8,quality-100/prime/economy-and-policy/law-in-the-time-of-recession-going-beyond-monetary-and-fiscal-policy-to-boost-aggregate-demand.jpg', 'Nuevas regulaciones fiscales para incentivar la inversión', NOW(), 19, 0, 5, 'Estímulo a la inversión empresarial', 'Se han implementado nuevas regulaciones fiscales con el objetivo de fomentar la inversión y el crecimiento económico. Estas medidas incluyen reducciones de impuestos para las empresas, incentivos para la inversión en sectores estratégicos y la simplificación de trámites administrativos. Las autoridades buscan crear un entorno propicio para los negocios y estimular la actividad empresarial.'),
	(4, 'https://i.ytimg.com/vi/ICplV91JiTc/maxresdefault.jpg', 'Emprendedores exitosos comparten sus experiencias', NOW(), 23, 0, 5, 'Inspiración y consejos para emprendedores', 'Destacados emprendedores han compartido sus historias de éxito y brindado consejos a aquellos que desean iniciar su propio negocio. Estas experiencias ofrecen inspiración y conocimientos prácticos sobre diversos aspectos del emprendimiento, como la planificación, la financiación, la gestión de equipos y la superación de desafíos. Las lecciones aprendidas por estos emprendedores pueden ser valiosas para quienes están en el inicio de su camino empresarial.'),
	(4, 'https://estaticos-cdn.elperiodico.com/clip/74c03414-1ed9-4703-a287-2f521a2b7177_alta-libre-aspect-ratio_default_0.jpg', 'Crecimiento del mercado de criptomonedas', NOW(), 27, 0, 5, 'Auge de las criptomonedas', 'El mercado de criptomonedas continúa experimentando un crecimiento significativo. El interés en las criptodivisas, como Bitcoin y Ethereum, ha aumentado tanto entre inversores institucionales como individuales. Este crecimiento ha llevado a una mayor aceptación y adopción de las criptomonedas como una forma legítima de inversión y medio de intercambio. Sin embargo, también plantea desafíos regulatorios y de seguridad que deben abordarse.'),
	(4, 'https://diariobitcoin.b-cdn.net/wp-content/uploads/2021/04/dinero-dolares-millonario-unsplash.jpg', 'Nueva empresa tecnológica recibe financiamiento millonario', '2022-06-16 00:23:10', 21, 0, 5, 'Impulso a la innovación tecnológica', 'Una empresa emergente en el sector tecnológico ha obtenido una importante financiación de capital de riesgo. Esta inversión millonaria respalda el desarrollo de nuevas tecnologías y soluciones innovadoras en áreas como inteligencia artificial, blockchain y energías renovables. El éxito de esta empresa refuerza la importancia de la innovación y el papel de la tecnología en la economía actual.'),
    (4, 'https://static.hosteltur.com/app/public/uploads/img/posts/2022/09/14/L_135647_sector-turistico.jpg', 'Crecimiento del sector turístico impulsa la economía local', NOW(), 0, 0, 5, 'Aumento en el turismo', 'El sector turístico ha experimentado un crecimiento significativo en los últimos meses, lo que está impulsando la economía local. El aumento en el número de visitantes ha generado mayores ingresos para las empresas relacionadas con el turismo, como hoteles, restaurantes y agencias de viajes. Esta tendencia positiva se espera que continúe en los próximos años, beneficiando a la economía del país.'),
	(4, 'https://apcp.es/wp-content/uploads/2022/08/imagen-destacada.png', 'Nuevas políticas energéticas promueven la transición hacia fuentes renovables', NOW(), 0, 0, 5, 'Impulso a la sostenibilidad', 'El gobierno ha implementado nuevas políticas energéticas con el objetivo de fomentar la adopción de fuentes renovables. Estas medidas incluyen incentivos para la instalación de paneles solares, la promoción de vehículos eléctricos y la reducción de emisiones contaminantes. Se espera que estas políticas impulsen la transición hacia una economía más sostenible y contribuyan a la lucha contra el cambio climático.'),
    (4, 'https://images.ecestaticos.com/18n1SlHi1E9eLrpugp1AwK0dSjY=/0x0:908x564/1440x810/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F1b4%2Fee5%2Fffb%2F1b4ee5ffb35c7d3a1e4e24766c47c8be.jpg', 'Sector manufacturero experimenta un aumento en la producción', NOW(), 0, 0, 5, 'Recuperación de la industria', 'El sector manufacturero ha registrado un aumento significativo en la producción durante el último trimestre. Este incremento se debe a una mayor demanda de productos tanto a nivel nacional como internacional. La recuperación de la industria manufacturera es un indicador positivo para la economía, ya que impulsa el empleo y estimula el crecimiento económico.'),
	(4, 'https://static.vecteezy.com/system/resources/previews/007/441/621/non_2x/invest-in-our-planet-lettering-quote-earth-day-theme-card-earth-illustration-green-economy-concept-vector.jpg', 'Inversiones en infraestructura impulsan el desarrollo regional', NOW(), 0, 0, 5, 'Mejora de la infraestructura', 'Se han realizado inversiones significativas en proyectos de infraestructura a nivel regional. Estas inversiones abarcan la construcción y mejora de carreteras, puertos, aeropuertos y redes de transporte. Se espera que estas mejoras en la infraestructura impulsen el desarrollo económico de las regiones, faciliten el comercio y promuevan la creación de empleo.'),
	(4, 'https://blog.insightswm.com/wp-content/uploads/2022/06/insights_insights_image_0.jpeg', 'Aumento en la inversión en investigación y desarrollo', NOW(), 0, 0, 5, 'Impulso a la innovación', 'Las empresas están incrementando su inversión en investigación y desarrollo (I+D) para impulsar la innovación y mantenerse competitivas en el mercado global. Estas inversiones se destinan al desarrollo de nuevas tecnologías, productos y procesos, lo que puede generar avances significativos en diversos sectores y contribuir al crecimiento económico a largo plazo.'),
	(4, 'https://blog.bancosabadell.com/.a/6a00e009801040883302b7519e01cb200c-800wi', 'Crecimiento del mercado de exportaciones en el sector agrícola', NOW(), 0, 0, 5, 'Oportunidades en el comercio internacional', 'El sector agrícola ha experimentado un crecimiento significativo en las exportaciones durante el último año. La demanda de productos agrícolas ha aumentado en los mercados internacionales, lo que ha generado oportunidades para los productores y ha impulsado el desarrollo de nuevas estrategias de comercialización en el sector.'),
	(4, 'https://s3.ppllstatics.com/elcorreo/www/multimedia/202212/23/media/cortadas/inteligencia-artificial-kI3C-U19053902133bBD-1248x770@RC.jpg', 'Avances en la inteligencia artificial transforman la industria', NOW(), 0, 0, 5, 'Innovación tecnológica', 'Los avances en inteligencia artificial están transformando diversos sectores industriales. Desde la automatización de procesos hasta la mejora en la toma de decisiones basada en datos, la inteligencia artificial está generando eficiencias y oportunidades de crecimiento para las empresas que adoptan estas tecnologías.'),
    (4, 'https://4.bp.blogspot.com/-K8whwQUhJRU/WohUOSgaj1I/AAAAAAAAHt8/KAWqSvkz-bYKA4mmtviufrSGXoy9nLt0wCLcBGAs/s1600/Politica%2Bfiscal%2Bexpansiva%2By%2Brestrictiva.png', 'Nuevas políticas fiscales buscan incentivar la inversión extranjera', NOW(), 0, 0, 5, 'Atracción de capitales', 'El gobierno ha implementado políticas fiscales favorables para atraer inversión extranjera directa al país. Estas políticas incluyen incentivos fiscales, simplificación de trámites y promoción de sectores estratégicos. Se espera que estas medidas impulsen la llegada de capitales, generen empleo y estimulen el crecimiento económico.'),
	(4, 'https://iencuentro.es/wp-content/uploads/2018/03/Mercado_Inmobiliario_2018.jpeg', 'Mercado inmobiliario experimenta un aumento en la demanda', NOW(), 0, 0, 5, 'Boom del sector inmobiliario', 'El mercado inmobiliario ha experimentado un aumento en la demanda de propiedades tanto residenciales como comerciales. Factores como la baja en las tasas de interés y el crecimiento económico están impulsando la inversión en bienes raíces. Este auge del sector inmobiliario representa oportunidades tanto para desarrolladores como para compradores e inversores.'),
	(4, 'https://thestandardcio.com/wp-content/uploads/sites/2/2018/06/Banking-Data-768x384.jpg', 'Digitalización de los servicios financieros revoluciona la banca', NOW(), 0, 0, 5, 'Transformación digital', 'La digitalización de los servicios financieros ha revolucionado la industria bancaria. Desde aplicaciones móviles hasta pagos digitales y préstamos en línea, los avances tecnológicos están cambiando la forma en que las personas gestionan sus finanzas. Esta transformación digital ofrece mayor comodidad y agilidad en las transacciones, así como nuevas oportunidades de negocio para las instituciones financieras.'),
	(4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJjtwtOoZ_7SpNiJ8qPu2vj4udfcJfCBZl4xAo8HVUtkel6R4bjXnd-xlv0JxMOhnv6nU&usqp=CAU', 'Descubren nueva especie marina en el océano Atlántico', NOW(), 0, 0, 3, 'Exploración marina', 'Un equipo de científicos ha descubierto una nueva especie marina en las profundidades del océano Atlántico. El hallazgo representa un avance significativo en el conocimiento de la biodiversidad marina y destaca la importancia de la conservación de los ecosistemas marinos.'),
    (4, 'https://i.ytimg.com/vi/BAoyYIx7zaw/maxresdefault.jpg', 'Protestas masivas exigen cambios en la política educativa', NOW(), 0, 0, 1, 'Movilización estudiantil', 'Miles de estudiantes y profesores se han manifestado en las calles exigiendo cambios en la política educativa del país. Las protestas buscan mejoras en la calidad de la educación, aumento de presupuesto para las instituciones educativas y mayor participación estudiantil en las decisiones que afectan su formación académica.'),
	(4, 'https://www.debate.com.mx/__export/1644519695015/sites/debate/img/2022/02/10/huracanes_crop1644519282630.jpeg_423682103.jpeg', 'Desastre natural deja miles de personas damnificadas', NOW(), 0, 0, 1, 'Emergencia humanitaria', 'Un desastre natural, como un terremoto o inundación, ha afectado a una región del país dejando miles de personas damnificadas. Las autoridades están coordinando esfuerzos para brindar ayuda humanitaria, restablecer servicios básicos y reconstruir las áreas afectadas.'),
    (4, 'https://static.hoy.es/solidario/multimedia/202302/03/media/20230203115138_f1.jpg', 'Avances en la investigación contra el cáncer', NOW(), 0, 0, 2, 'Salud y bienestar', 'Científicos han logrado avances significativos en la investigación contra el cáncer. Nuevas terapias y tratamientos están mostrando promesas en la lucha contra esta enfermedad, brindando esperanza a pacientes y sus familias.'),
    (4, 'https://imagenes.elpais.com/resizer/QrBnqkWanAkBD8QvwV4X6Hk8KTI=/980x980/cloudfront-eu-central-1.images.arcpublishing.com/prisa/HXD5JK7WIFASXOFTJGIF57OE2M.jpg', 'Polémica ley genera debate en el Congreso', NOW(), 0, 0, 1, 'Legislación controvertida', 'Una nueva ley propuesta ha generado un intenso debate en el Congreso. Diversos sectores de la sociedad expresan sus opiniones a favor y en contra de la legislación, que aborda temas de relevancia para el país, como derechos civiles, medio ambiente o economía.'),
	(4, 'https://i.ytimg.com/vi/0VyAB9SWbNA/maxresdefault.jpg', 'Polémica ley genera debate en el Congreso', NOW(), 0, 0, 1, 'Legislación controvertida', 'Una nueva ley propuesta ha generado un intenso debate en el Congreso. Diversos sectores de la sociedad expresan sus opiniones a favor y en contra de la legislación, que aborda temas de relevancia para el país, como derechos civiles, medio ambiente o economía.'),
    (4, 'https://givt.com/app/uploads/2020/02/bigest-airports.jpg', 'Nuevas medidas de seguridad implementadas en aeropuertos', NOW(), 0, 0, 1, 'Seguridad aérea', 'Con el objetivo de fortalecer la seguridad en los vuelos, se han implementado nuevas medidas en los aeropuertos. Estas incluyen tecnologías avanzadas de detección, protocolos de revisión más rigurosos y mayor capacitación para el personal de seguridad aeroportuaria.'),
    (4, 'https://statics-cuidateplus.marca.com/cms/styles/ratio_43/azblob/contaminacion-ilustracion.jpg.webp?itok=l0elgOfc', 'Estudio revela impacto negativo de la contaminación en la salud', NOW(), 0, 0, 1, 'Medio ambiente y salud', 'Un estudio científico ha evidenciado los efectos perjudiciales de la contaminación ambiental en la salud humana. Se ha demostrado una asociación entre la exposición a altos niveles de contaminantes y el aumento de enfermedades respiratorias, cardiovasculares y otros problemas de salud.'),
    (4, 'https://trevolintegra.com/wp-content/uploads/2017/04/responsabilidad-social-300x167.jpg', 'Celebridades se unen para apoyar campaña de concientización social', NOW(), 0, 0, 1, 'Responsabilidad social', 'Reconocidas celebridades del ámbito artístico se han sumado a una campaña de concientización social. Su participación busca crear conciencia sobre temas importantes, como la igualdad de género, la inclusión social o el cuidado del medio ambiente.'),
    (4, 'https://storage.ning.com/topology/rest/1.0/file/get/2663519188?profile=RESIZE_710x', 'Descubren yacimiento arqueológico de gran importancia histórica', NOW(), 0, 0, 1, 'Patrimonio cultural', 'Arqueólogos han descubierto un yacimiento de gran relevancia histórica que ofrece nuevos conocimientos sobre civilizaciones antiguas. El hallazgo incluye restos arqueológicos, artefactos y estructuras que ayudan a comprender mejor el pasado de la región.'),
    (4, 'https://www.uso.es/wp-content/uploads/2022/09/sindicato-uso-energias-renovables-emergencia-climatica.png', 'Aumento en la adopción de energías renovables a nivel mundial', NOW(), 0, 0, 3, 'Sostenibilidad energética', 'La adopción de fuentes de energía renovables, como la solar y la eólica, ha experimentado un importante aumento a nivel mundial. Este crecimiento refleja el compromiso de los países por reducir la dependencia de los combustibles fósiles y mitigar los efectos del cambio climático.'),
	(4, 'https://proximahost.es/blog/wp-content/uploads/2021/06/Redes-sociales.jpg', 'Debate internacional sobre la regulación de las redes sociales', NOW(), 0, 0, 1, 'Tecnología y sociedad', 'El papel y la regulación de las redes sociales están en el centro de un debate internacional. Diversos actores plantean la necesidad de establecer normativas que protejan la privacidad, combatan la desinformación y promuevan un uso responsable de estas plataformas digitales.'),
    (1, 'https://www.incart.gob.do/wp-content/uploads/2021/01/Imagen-Articulo-.-02-01-2121-scaled-1.jpg', 'Descubren nuevo tratamiento prometedor contra el cáncer', NOW(), 0, 0, 2, 'Investigación médica', 'Investigadores han desarrollado un nuevo tratamiento que muestra resultados prometedores en la lucha contra el cáncer. Esta terapia innovadora utiliza técnicas avanzadas para atacar selectivamente las células cancerosas, brindando nuevas esperanzas a los pacientes.'),
    (1, 'https://www.saludymedicina.org/wp-content/uploads/2021/08/images.jpg', 'Prevención y control de enfermedades infecciosas en aumento', NOW(), 0, 0, 2, 'Salud pública', 'Los esfuerzos en prevención y control de enfermedades infecciosas se han intensificado. Se están implementando programas de vacunación, promoción de medidas higiénicas y seguimiento epidemiológico para proteger a la población y evitar la propagación de enfermedades.'),
    (1, 'https://image.isu.pub/170324204832-ad97e30d613d9c80daa404513a8c6d00/jpg/page_1.jpg', 'Avances en la investigación de enfermedades neurodegenerativas', NOW(), 0, 0, 2, 'Neurociencia', 'Los científicos han logrado avances significativos en la investigación de enfermedades neurodegenerativas, como el Alzheimer y el Parkinson. Estos descubrimientos permiten una mejor comprensión de las causas y el desarrollo de posibles tratamientos para estas condiciones.'),
    (1, 'https://charter100grancanaria.org/wp-content/uploads/2022/09/problemasocial-k8tB-U1701150585637ioH-624x385@Canarias7.jpeg', 'Campañas de concientización sobre la importancia de la salud mental', NOW(), 0, 0, 2, 'Salud mental', 'Se han puesto en marcha campañas de concientización para promover la importancia de la salud mental. Estas iniciativas buscan reducir el estigma asociado a los trastornos mentales y fomentar el acceso a servicios de apoyo psicológico y emocional.'),
    (1, 'https://ginequalitas.com/images/blog/tiposenfermedadesgeneticas4.jpg', 'Avances en terapias génicas para enfermedades hereditarias', NOW(), 0, 0, 2, 'Genética y medicina', 'La investigación en terapias génicas ha logrado avances significativos en el tratamiento de enfermedades hereditarias. Estas terapias buscan corregir o compensar las anomalías genéticas, brindando esperanza a pacientes y sus familias.'),
    (2, 'https://mundomarfan.files.wordpress.com/2018/01/vida1.png', 'Desarrollo de nuevas tecnologías médicas para mejorar la calidad de vida', NOW(), 0, 0, 2, 'Innovación médica', 'Se están desarrollando nuevas tecnologías médicas que tienen como objetivo mejorar la calidad de vida de los pacientes. Estas innovaciones abarcan desde dispositivos médicos hasta aplicaciones móviles y sistemas de monitoreo remoto.'),
    (2, 'https://i.ytimg.com/vi/qv25YVfH-CE/maxresdefault.jpg', 'Investigación en terapias alternativas complementarias a la medicina tradicional', NOW(), 0, 0, 2, 'Medicina integrativa', 'La investigación en terapias alternativas complementarias a la medicina tradicional está en aumento. Se estudia la eficacia y seguridad de enfoques como la acupuntura, la homeopatía y la medicina herbal en el tratamiento de diversas condiciones de salud.'),
    (2, 'https://i2.wp.com/sbco.org.br/wp-content/uploads/2021/05/conheca-os-tipos-de-cancer-de-mama-e-quando-e-necessario-cirurgia.jpg?w=382&quality=95&ssl=1', 'Avances en la detección temprana del cáncer de mama', NOW(), 0, 0, 2, 'Salud de la mujer', 'Se han logrado avances significativos en la detección temprana del cáncer de mama. Nuevas técnicas de imagen y biomarcadores permiten identificar lesiones malignas en etapas iniciales, mejorando las tasas de supervivencia y el tratamiento de esta enfermedad.'),
	(2, 'https://www.yoinfluyo.com/wp-content/uploads/2019/11/dec188140cadbe0e52d802f53c43ec86-1200x900.jpg', 'Iniciativas para promover la donación de órganos', NOW(), 0, 0, 2, 'Trasplantes', 'Se están implementando iniciativas para promover la donación de órganos y aumentar la disponibilidad de trasplantes. Campañas de concientización y mejoras en los sistemas de registro y distribución de órganos están contribuyendo a salvar vidas y mejorar la calidad de vida de pacientes en lista de espera.'),
	(2, 'https://cdn.euroinnova.edu.es/img/subidasEditor/euroinnova-_4_-1651132462.webp', 'Investigación en nuevos antibióticos para combatir la resistencia bacteriana', NOW(), 0, 0, 2, 'Microbiología', 'La investigación se centra en el desarrollo de nuevos antibióticos para hacer frente a la creciente resistencia bacteriana. Se buscan soluciones efectivas para combatir infecciones que han dejado de responder a los tratamientos convencionales.'),
	(2, 'https://www.eltiempo.com/files/image_640_428/uploads/2022/12/15/639b8b9176d40.jpeg', 'Avances en la medicina regenerativa para la reparación de tejidos y órganos', NOW(), 0, 0, 2, 'Medicina regenerativa', 'La medicina regenerativa ha experimentado avances significativos en la reparación de tejidos y órganos. La utilización de células madre y la ingeniería de tejidos ofrecen nuevas posibilidades para el tratamiento de lesiones y enfermedades degenerativas.'),
	(2, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzP2qxlNAVvGgXY8pEB0ephpC-hyAZZ85JrQ&usqp=CAU', 'Desarrollo de terapias innovadoras para enfermedades raras', NOW(), 0, 0, 2, 'Enfermedades raras', 'Se están desarrollando terapias innovadoras para enfermedades raras que carecen de tratamientos efectivos. La investigación se enfoca en terapias génicas, terapias celulares y otras estrategias para mejorar la calidad de vida de los pacientes.'),
	(2, 'https://www.us.es/sites/default/files/noticia/Salud%20Inteligencia%20artificial_0.jpg', 'Investigación en el uso de inteligencia artificial en la medicina', NOW(), 0, 0, 2, 'Tecnología médica', 'La inteligencia artificial está siendo investigada para su aplicación en la medicina. Algoritmos y modelos de aprendizaje automático pueden ayudar en el diagnóstico temprano, el pronóstico de enfermedades y la optimización de tratamientos médicos.'),
	(3, 'https://www.consalud.es/uploads/s1/73/53/92/conoce-la-epidemiologia.jpeg', 'Estrategias de prevención y control de enfermedades transmisibles', NOW(), 0, 0, 2, 'Epidemiología', 'Se están implementando estrategias de prevención y control de enfermedades transmisibles, como el desarrollo de vacunas, la mejora de la vigilancia epidemiológica y la promoción de prácticas de higiene.'),
    (3, 'https://clinicarozalen.com/wp-content/uploads/2023/01/images-1.jpg', 'Investigación en terapias no invasivas para el tratamiento del dolor crónico', NOW(), 0, 0, 2, 'Dolor crónico', 'La investigación se centra en el desarrollo de terapias no invasivas para aliviar el dolor crónico. Técnicas como la estimulación magnética transcraneal y la estimulación nerviosa eléctrica ofrecen alternativas a los tratamientos convencionales.'),
    (3, 'https://www.lavanguardia.com/files/content_image_mobile_filter/uploads/2020/10/08/5fb2858f3a78b.jpeg', 'Avances en la telemedicina para brindar atención médica a distancia', NOW(), 0, 0, 2, 'Telemedicina', 'La telemedicina ha experimentado avances significativos, permitiendo brindar atención médica a distancia. La tecnología digital facilita la comunicación entre médicos y pacientes, especialmente en áreas remotas o de difícil acceso.'),
    (3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsS77kvvOLOYWe9jKgHAAvgPK5AQf21RGWEzvdD4nJEIupberIzIzN-2Qg5y7rTtTk-Yw&usqp=CAU', 'Investigación en terapias personalizadas basadas en el perfil genético del paciente', NOW(), 0, 0, 2, 'Medicina de precisión', 'La investigación se enfoca en el desarrollo de terapias personalizadas basadas en el perfil genético del paciente. Esto permite tratamientos más efectivos y reducción de efectos secundarios en comparación con enfoques generalizados.'),
    (3, 'https://www.dentalgalindo.com/wp-content/uploads/2022/04/alzheimer01.jpg', 'Avances en la detección y tratamiento del Alzheimer', NOW(), 0, 0, 2, 'Enfermedades neurodegenerativas', 'Se han logrado avances en la detección temprana y el tratamiento del Alzheimer. Nuevas técnicas de imagen cerebral y terapias farmacológicas ofrecen esperanza para ralentizar la progresión de esta enfermedad neurodegenerativa.'),
    (4, 'https://static.abc.es/media/bienestar/2019/09/17/futbol-1-kU3C--1200x630@abc.jpg', 'Equipo de fútbol gana el campeonato nacional', NOW(), 0, 0, 6, 'Fútbol', 'El equipo de fútbol local se consagra campeón nacional tras una destacada temporada. Los jugadores y el cuerpo técnico celebran el logro y son reconocidos por su dedicación y habilidad en el campo de juego.'),
    (4, 'https://lh5.googleusercontent.com/3DIsuXhksmAg2PRROwl4r95Ev_CBUx1Y8a6jzRYoHGonFjHhY6xoRQBTA-4gyynkIvUiyK2TNxLopJ9WtdNb2W_tBmENtvjmy3Kw0K-WvhoDtbrl2Af5XVcdz7FYDems4ttui1N4', 'Juegos Olímpicos: Atleta rompe récord mundial en salto de altura', NOW(), 0, 0, 6, 'Atletismo', 'Un atleta de renombre mundial establece un nuevo récord en salto de altura durante los Juegos Olímpicos. Su destacada actuación y superación personal asombran al público y lo convierten en una leyenda del deporte.'),
    (4, 'https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg)/origin-imgresizer.eurosport.com/2022/06/15/3393293-69346028-2560-1440.jpg', 'Tenista se consagra campeón en torneo de Grand Slam', NOW(), 0, 0, 6, 'Tenis', 'Un talentoso tenista alcanza la cima al ganar un torneo de Grand Slam. Su habilidad técnica, resistencia y mentalidad competitiva lo llevan a la victoria y lo posicionan como uno de los mejores en su disciplina.'),
	(4, 'https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2022/12/14/16710302791565.jpg', 'Récord mundial en natación: nadador completa travesía en tiempo récord', NOW(), 0, 0, 6, 'Natación', 'Un nadador audaz rompe el récord mundial al completar una desafiante travesía en tiempo récord. Su determinación y destreza en el agua lo convierten en un referente para la comunidad de nadadores.'),
	(4, 'https://s1.eestatic.com/2023/06/22/deportes/baloncesto/773433625_234177763_1706x960.jpg', 'Equipo de baloncesto femenino gana el campeonato internacional', NOW(), 0, 0, 6, 'Baloncesto', 'El equipo de baloncesto femenino de un país se consagra campeón en un prestigioso torneo internacional. Su talento, trabajo en equipo y dedicación inspiran a jóvenes deportistas y promueven la igualdad de género en el deporte.'),
	(4, 'https://d2p6e6u75xmxt8.cloudfront.net/6/2021/08/Tokyo-peloton-profimedia-0623070356-CvR-1024x450.jpg', 'Ciclista profesional gana la vuelta ciclística', NOW(), 0, 0, 6, 'Ciclismo', 'Un ciclista profesional se lleva la victoria en una importante vuelta ciclística. Su resistencia, estrategia y destreza en la bicicleta lo convierten en un referente para los amantes de este deporte.'),
	(4, 'https://cadenaser.com/resizer/7QjwyBD_MRg1lCtCZrEgW6c36RU=/736x552/filters:format(jpg):quality(70)/cloudfront-eu-central-1.images.arcpublishing.com/prisaradio/STAS67FMYFDR5DCBUYTMKCMNWE.jpg', 'Jugador de golf logra un hoyo en uno durante torneo de élite', NOW(), 0, 0, 6, 'Golf', 'Un destacado jugador de golf sorprende al lograr un hoyo en uno durante un torneo de élite. Su precisión y habilidad en el juego lo posicionan como uno de los mejores golfistas del mundo.'),
	(4, 'https://img.freepik.com/fotos-premium/atleta-rugby-campo-juego-deportivo-equipo-hombres-corriendo-jugador-puntua-intento-aptitud-pelota-partido-campeonato-ejercicio-activo-al-aire-libre-trabajo-equipo-accion-energia-vitores_590464-150695.jpg?w=2000', 'Equipo de rugby se consagra campeón de liga', NOW(), 0, 0, 6, 'Rugby', 'El equipo de rugby local se alza como campeón de liga tras una temporada llena de emociones y partidos intensos. Su fuerza, estrategia y espíritu deportivo los llevan a la gloria en este deporte de contacto.'),
	(4, 'https://ponferradahoy.com/wp-content/uploads/2022/08/boxeo.jpg', 'Boxeador obtiene el título mundial en su categoría de peso', NOW(), 0, 0, 6, 'Boxeo', 'Un talentoso boxeador alcanza la cima al obtener el título mundial en su categoría de peso. Su agilidad, resistencia y técnica de golpeo lo convierten en un referente dentro del ring.'),
	(4, 'https://e7.pngegg.com/pngimages/796/634/png-clipart-canadian-national-men-s-hockey-team-ice-hockey-player-los-angeles-kings-defenseman-drew-mcintyre.png', 'Equipo de hockey sobre hielo gana el campeonato regional', NOW(), 0, 0, 6, 'Hockey sobre hielo', 'El equipo de hockey sobre hielo de una ciudad se corona campeón en el campeonato regional. Sus habilidades en patinaje, manejo del puck y trabajo en equipo los llevan a la victoria en este deporte de velocidad y estrategia.'),
	(4, 'https://www.enarmoniapsicologos.com/upload/post-750992241.jpg', 'Investigación revela los beneficios de la terapia cognitivo-conductual', NOW(), 0, 0, 8, 'Terapia cognitivo-conductual', 'Un estudio científico reciente demuestra los beneficios de la terapia cognitivo-conductual en el tratamiento de trastornos de ansiedad y depresión. Los resultados resaltan la eficacia de esta técnica terapéutica y su impacto positivo en la salud mental de los pacientes.'),
	(4, 'https://www.cdc.gov/ncbddd/spanish/childdevelopment/img/kids-painted-smileys-hands-500px.jpg?_=22340', 'Psicólogo renombrado presenta nueva teoría sobre el desarrollo infantil', NOW(), 0, 0, 8, 'Desarrollo infantil', 'Un reconocido psicólogo presenta una nueva teoría sobre el desarrollo infantil, que ofrece una perspectiva innovadora y amplía el entendimiento en este campo. Sus investigaciones y aportes abren nuevas puertas para comprender cómo los niños crecen y se desarrollan emocionalmente.'),
	(4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVArEymigcwDtzGHIqIHVOGvmFX5s-j3I1fHxjsxsuzjOS0xbZLSaXiVVHPQKVq4Bs760&usqp=CAU', 'Técnicas de relajación para reducir el estrés en el trabajo', NOW(), 0, 0, 8, 'Estrés laboral', 'Expertos en psicología presentan técnicas de relajación efectivas para reducir el estrés en el entorno laboral. Estas prácticas permiten a los trabajadores manejar la presión, mejorar su bienestar emocional y aumentar su productividad en el trabajo.'),
	(4, 'https://petitfitbycris.com/wp-content/uploads/2019/11/autoestima.jpg', 'Estudio revela la influencia de los medios de comunicación en la autoestima', NOW(), 0, 0, 8, 'Autoestima', 'Una investigación analiza la influencia de los medios de comunicación en la construcción de la autoestima en la sociedad actual. Los resultados destacan la importancia de promover una imagen corporal realista y fomentar la aceptación personal para mejorar la salud mental de las personas.'),
	(4, 'https://humanidades.com/wp-content/uploads/2017/05/inteligencia-emocional-e1568426958449-800x400.jpg', 'Importancia de la inteligencia emocional en el ámbito laboral', NOW(), 0, 0, 8, 'Inteligencia emocional', 'Expertos en psicología resaltan la importancia de la inteligencia emocional en el ámbito laboral. Habilidades como el manejo de emociones, la empatía y la comunicación asertiva son fundamentales para el éxito profesional y el bienestar en el entorno de trabajo.'),
	(4, 'https://psynthesispsicologia.es/wp-content/uploads/2020/11/Diferencias-entre-estres-y-ansiedad.png', 'Aplicación móvil ayuda a controlar la ansiedad y el estrés', NOW(), 0, 0, 8, 'Salud mental', 'Una nueva aplicación móvil desarrollada por psicólogos ofrece herramientas y ejercicios prácticos para controlar la ansiedad y el estrés. Esta tecnología brinda apoyo a las personas en su bienestar emocional, proporcionando técnicas de relajación y seguimiento personalizado.'),
	(4, 'https://depsicologia.com/wp-content/uploads/PsicologiaPositiva-600x400.jpg', 'La psicología positiva como enfoque para promover la felicidad', NOW(), 0, 0, 8, 'Psicología positiva', 'La psicología positiva se posiciona como un enfoque efectivo para promover la felicidad y el bienestar. Esta disciplina se centra en identificar y potenciar fortalezas personales, cultivar relaciones positivas y encontrar sentido y propósito en la vida.'),
    (4, 'https://s1.ppllstatics.com/leonoticias/www/multimedia/202011/19/media/cortadas/diferencias-meditar-mindfulness_peque-kTpG-U120815671890yfH-1248x770@RC.jpg', 'Los beneficios del mindfulness en la reducción del estrés', NOW(), 0, 0, 8, 'Mindfulness', 'Diversos estudios respaldan los beneficios del mindfulness en la reducción del estrés y la mejora de la salud mental. Esta práctica de atención plena ayuda a las personas a desarrollar una mayor conciencia del presente y a gestionar de manera efectiva las situaciones estresantes.'),
	(4, 'https://s3.amazonaws.com/s3.timetoast.com/public/uploads/photo/17865312/image/medium-c6071f91255043f64d4a8f4cbb91953e.jpg', 'La importancia de la terapia familiar en el tratamiento de trastornos', NOW(), 0, 0, 8, 'Terapia familiar', 'La terapia familiar se revela como una herramienta crucial en el tratamiento de trastornos y conflictos familiares. Este enfoque terapéutico busca fortalecer los vínculos familiares, mejorar la comunicación y resolver problemas para promover el bienestar de todos los miembros de la familia.'),
	(4, 'https://www.escuelaindustrialesupm.com/wp-content/uploads/2020/07/crecer-resiliencia-adversidad-1598x799.jpg', 'La resiliencia como factor clave en la superación de adversidades', NOW(), 0, 0, 8, 'Resiliencia', 'La resiliencia, entendida como la capacidad de adaptarse y superar adversidades, se destaca como un factor clave en la salud mental y el bienestar. La psicología ofrece herramientas y estrategias para fortalecer la resiliencia y afrontar de manera efectiva los desafíos de la vida.'),
	(4, 'https://revistaespejo.com/wp-content/uploads/2021/08/computadora-redes-sociales-depresion-2.jpg', 'El impacto de las redes sociales en la salud mental de los jóvenes', NOW(), 0, 0, 8, 'Redes sociales', 'Un análisis examina el impacto de las redes sociales en la salud mental de los jóvenes. Si bien estas plataformas ofrecen conexiones sociales y oportunidades, también pueden desencadenar ansiedad, baja autoestima y problemas de salud mental. Se exploran estrategias para un uso saludable de las redes sociales.'),
	(4, 'https://mipsicologomadrid.es/wp-content/uploads/2021/11/autocuidado.jpg', 'La importancia del autocuidado en la salud mental', NOW(), 0, 0, 8, 'Autocuidado', 'Se resalta la importancia del autocuidado en la promoción de la salud mental. A través de prácticas como el descanso adecuado, la alimentación balanceada, la actividad física y la gestión del estrés, las personas pueden mantener un equilibrio emocional y un bienestar general.'),
	(4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQygQf6CHLt6VXAna6_W_pjNfyzY9zEQ3nGdKwnpUJqAg2hMf59yzywtg82LyXi5jSUd8w&usqp=CAU', 'El impacto de la música en la salud mental y el estado de ánimo', NOW(), 0, 0, 8, 'Música', 'Se explora el impacto de la música en la salud mental y el estado de ánimo. La música puede ser utilizada como una herramienta terapéutica para reducir el estrés, mejorar el ánimo y promover el bienestar emocional.'),
	(4, 'https://rinconpsicologia.com/wp-content/uploads/2021/03/Tipos-de-limites-personales-1024x512.jpg', 'La importancia de establecer límites personales en las relaciones', NOW(), 0, 0, 8, 'Relaciones personales', 'Se analiza la importancia de establecer límites personales saludables en las relaciones. Establecer límites claros ayuda a proteger el bienestar emocional, mantener relaciones equilibradas y establecer expectativas realistas.'),
	(4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL1zeVQ7QVCnL5tdqnxbBvpiJ3oT6tEu4NQg&usqp=CAU', 'El impacto de la gratitud en la salud mental y el bienestar', NOW(), 0, 0, 8, 'Gratitud', 'Se destaca el impacto positivo de la gratitud en la salud mental y el bienestar general. Practicar la gratitud diariamente puede promover emociones positivas, reducir el estrés y fomentar relaciones saludables.'),
	(4, 'https://myspiralbox.com/wp-content/uploads/2021/01/estilo-de-vida-saludable-segu%CC%81n-la-OMS-1024x278-1.jpg', 'Consejos para llevar un estilo de vida saludable', NOW(), 0, 0, 9, 'Salud', 'Se ofrecen consejos prácticos para llevar un estilo de vida saludable. Estos incluyen mantener una alimentación equilibrada, hacer ejercicio regularmente, dormir lo suficiente y gestionar el estrés de manera efectiva.'),
	(4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGLpVute1K3LA57UXjH2_yMxP5roX2b7gqHQ&usqp=CAU', 'Ideas para decorar tu hogar y crear un ambiente acogedor', NOW(), 0, 0, 9, 'Decoración del hogar', 'Se comparten ideas y consejos para decorar tu hogar y crear un ambiente acogedor. Desde la elección de colores y muebles hasta la organización del espacio, estos consejos te ayudarán a transformar tu hogar en un lugar acogedor.'),
	(4, 'https://www.ieie.eu/wp-content/uploads/2021/09/infografia-aumentar-la-productividad-personal-ieie.jpg', 'Consejos para mejorar la productividad y organización personal', NOW(), 0, 0, 9, 'Productividad personal', 'Se ofrecen consejos prácticos para mejorar la productividad y la organización personal. Estas estrategias te ayudarán a aprovechar al máximo tu tiempo, establecer metas claras y mantener un equilibrio entre el trabajo y la vida personal.'),
	(4, 'https://buensalud.es/wp-content/uploads/2020/05/recetas-saludables.jpg', 'Ideas de recetas saludables y deliciosas para el día a día', NOW(), 0, 0, 9, 'Recetas saludables', 'Se presentan ideas de recetas saludables y deliciosas para incorporar en tu día a día. Estas recetas incluyen ingredientes nutritivos y sabrosos, ayudándote a mantener una alimentación equilibrada sin renunciar al sabor.'),
	(4, 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEio16yx5qCAM9wsTQ9d4F_e6CQR3Mcy-Jjzzt-ggzIZB1mcsHH0VhRl02W0-ub5-oCvIOfQRYEvyGbVzFjNj11uTZOJ897NC3qTFwgQKkG8vORReZDPC6HtEP81nBVq9ZL9fGd6IWM-Hvns9qGh3VUtFw486mpYvUgC8zXJjfY-S9bdc5wOEuKnBUT9hA/s1920/consejos%20de%20moda.jpg', 'Consejos de moda para lucir bien en cualquier ocasión', NOW(), 0, 0, 9, 'Moda', 'Se brindan consejos de moda para lucir bien en cualquier ocasión. Desde la elección de prendas hasta la combinación de colores y estilos, estos consejos te ayudarán a reflejar tu personalidad a través de tu estilo.'),
	(4, 'https://media.licdn.com/dms/image/C4E12AQGqoJ7OyMqeHg/article-cover_image-shrink_600_2000/0/1528197637920?e=2147483647&v=beta&t=5LmaIoFl421aNH-X5t2mgDIJm3dD_AFnsu6CDBj4vmA', 'Consejos para mantener una vida social equilibrada', NOW(), 0, 0, 9, 'Vida social', 'Se ofrecen consejos para mantener una vida social equilibrada. Estos consejos te ayudarán a cultivar relaciones saludables, establecer límites personales y encontrar un equilibrio entre el tiempo dedicado a ti mismo y a los demás.'),
	(4, 'https://i.ytimg.com/vi/vyPwa1rTlEo/sddefault.jpg', 'Ideas para realizar actividades de ocio y disfrutar de tu tiempo libre', NOW(), 0, 0, 9, 'Ocio', 'Se presentan ideas para realizar actividades de ocio y disfrutar de tu tiempo libre. Estas actividades van desde practicar deportes, explorar nuevos hobbies hasta disfrutar de momentos de relajación y autocuidado.'),
	(4, 'https://letslaw.es/wp-content/uploads/2019/12/atraccion-de-inversion-extranjera.jpeg', 'Nuevas medidas gubernamentales estimulan la inversión extranjera', NOW(), 0, 0, 5, 'Incentivos para inversores extranjeros', 'El gobierno ha implementado nuevas medidas con el objetivo de estimular la inversión extranjera en el país. Estas medidas incluyen la reducción de impuestos para los inversores internacionales, la simplificación de trámites burocráticos y la creación de incentivos económicos. Se espera que estas políticas fomenten la llegada de capital extranjero y impulsen el crecimiento económico.'),
	(4, 'https://www.prensa-latina.cu/wp-content/uploads/2022/10/crecimiento-economico.jpg', 'Informe económico pronostica crecimiento sostenido','2022-06-16 00:23:10', 24, 0, 5, 'Perspectivas positivas para la economía', 'Un informe económico reciente ha pronosticado un crecimiento sostenido en la economía global. Se prevé un aumento en la demanda de bienes y servicios, así como una mejora en las condiciones del mercado laboral. Estas perspectivas positivas son alentadoras para empresas y consumidores, ya que indican un mayor dinamismo en la actividad económica y oportunidades de crecimiento.');

SELECT * FROM news WHERE userId = 4;

SELECT * FROM news WHERE categoryId = 1;
SELECT * FROM news WHERE categoryId = 2;
SELECT * FROM news WHERE categoryId = 3;
SELECT * FROM news WHERE categoryId = 4;
SELECT * FROM news WHERE categoryId = 5;
SELECT * FROM news WHERE categoryId = 6;
SELECT * FROM news WHERE categoryId = 7;
SELECT * FROM news WHERE categoryId = 8;
SELECT * FROM news WHERE categoryId = 9;


SELECT * FROM news;
SELECT * FROM category;
SELECT * FROM users;



