USE hb_news;
INSERT INTO users (name, surname, email, password, imagenUrl, biography, active) 
VALUES 
('Eduardo', 'Castro Bianch', 'eduardo@gmail.com', '123', 'https://i.pinimg.com/170x/b9/9a/30/b99a309f679ff9154edc78d8db0575ea.jpg', 'Soy desarollador web', true),
('Guillermo', 'De La Rosa', 'guillermo@gmail.com', '123', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSDv22Pa8W1Tmf2uOYMLV-JuG1mMA6K8ezZg&usqp=CAU', 'Soy desarollador web', true),
('Fran', 'Valderrey', 'fran@gmail.com', '123', 'https://c.wallhere.com/photos/74/7a/V_for_Vendetta_mask_Guy_Fawkes_mask-76525.jpg!d', 'Soy desarollador web', true),
('David', 'Martinez Quiroga', 'david@gmail.com', '123', 'https://images.fineartamerica.com/images/artworkimages/medium/2/calimero-show-vesna-antic.jpg', 'Soy desarollador web', true);



INSERT INTO category (name) 
VALUES 
('Actualidad'),
('Sanidad'),
('Naturaleza'),
('Ciencia y tecnología'),
('Economía y negocios'),
('Deportes'),
('Entretenimiento'),
('Psicología'),
('Estilo de vida');



INSERT INTO news (userId, imagenUrl, title, publishDate, score, fakeNew, categoryId, introText, text)
VALUES
    (1, 'https://...jpg', 'Descubrimientos revolucionarios!!!', NOW(), 20, 0, 4, 'Descubrimientos revolucionarios en la Ciencia y Tecnología', 'El descubrimiento se basa en años de investigación intensiva y colaboración entre científicos de todo el mundo. Mediante el uso de tecnologías de vanguardia, los investigadores han logrado desarrollar un nuevo material con propiedades nunca antes vistas. Este material tiene el potencial de revolucionar diversas industrias, desde la medicina hasta la energía renovable. Además, sus características únicas podrían permitir avances significativos en áreas como la electrónica, la informática cuántica y la nanotecnología. Los expertos predicen que este descubrimiento marcará un hito en la historia de la ciencia y abrirá nuevas puertas hacia un futuro lleno de posibilidades innovadoras.'),
    (1, 'https://...jpg', 'Descubren nuevo planeta habitable en sistema solar cercano', NOW(), 20, 53, 4, 'Científicos han hecho un emocionante hallazgo!!', 'En un descubrimiento sin precedentes, astrónomos han identificado un nuevo planeta en un sistema solar cercano que presenta condiciones propicias para la existencia de vida. El exoplaneta, llamado Kepler-452b, se encuentra en la "zona habitable" alrededor de su estrella, lo que sugiere la posibilidad de que albergue agua líquida y sea adecuado para la vida tal como la conocemos. Este hallazgo plantea nuevas interrogantes sobre la existencia de otros mundos habitables y el potencial de encontrar formas de vida extraterrestre.'),
    (3, 'https://...jpg', 'Descubren vínculo entre la psicología y la salud física', '2022-06-16 00:23:10', 15, 0, 8, 'Interesante estudio en la categoría de Psicología.', 'Un nuevo estudio ha revelado una estrecha conexión entre la psicología y la salud física. Los investigadores encontraron que el bienestar mental y emocional de una persona puede tener un impacto significativo en su estado de salud general. Factores como el estrés, la ansiedad y la depresión pueden aumentar el riesgo de desarrollar enfermedades crónicas y disminuir la calidad de vida. Este descubrimiento resalta la importancia de abordar tanto la salud mental como la física para lograr un bienestar integral.'),
    (4, 'https://...jpg', 'Estreno de película taquillera', NOW(), 22, 0, 7, 'Emocionante estreno', 'La esperada película ha llegado a los cines y ha cautivado al público de todo el mundo. Con efectos especiales impresionantes, una trama emocionante y actuaciones destacadas, esta película promete ser uno de los éxitos de taquilla del año. Los fanáticos han elogiado la calidad cinematográfica y están ansiosos por ver las próximas entregas de la saga. Sin duda, este estreno ha generado gran entusiasmo y expectativas en el mundo del entretenimiento.'),
    (3, 'https://...jpg', 'Investigadores descubren nuevos avances en el campo de la psicología', NOW(), 28, 0, 8, 'Importantes avances en el campo de la Psicología.', 'Un equipo de investigadores ha logrado importantes avances en el campo de la psicología con su último estudio. Mediante la utilización de nuevas técnicas de investigación y la aplicación de teorías innovadoras, han obtenido resultados prometedores que podrían tener un impacto significativo en el tratamiento de trastornos mentales y el bienestar emocional. Estos hallazgos abren nuevas perspectivas para la psicología y brindan esperanza a aquellos que luchan con problemas de salud mental.'),
    (4, 'https://...jpg', 'Estrella de cine aclamada recibe premio a la trayectoria', NOW(), 19, 0, 7, 'Reconocimiento a una estrella de cine', 'Una de las estrellas más queridas de la industria del cine ha sido honrada con un premio a su destacada trayectoria. Esta reconocida actriz ha cautivado a audiencias de todo el mundo con sus interpretaciones memorables y su talento excepcional. Su contribución a la industria del entretenimiento ha sido invaluable y su legado perdurará en la historia del cine. Este premio es un merecido reconocimiento a su dedicación y talento.'),
    (1, 'https://...jpg', 'Avances tecnológicos revolucionan la industria', NOW(), 24, 0, 4, 'Innovación tecnológica', 'Los avances tecnológicos continúan transformando diversas industrias, desde la medicina hasta la comunicación. Investigadores y empresas han desarrollado nuevas soluciones y dispositivos que mejoran la calidad de vida de las personas y optimizan los procesos en diferentes sectores. Estos avances revolucionarios prometen abrir nuevas oportunidades y desafíos en un mundo cada vez más digitalizado y conectado.'),
    (2, 'https://...jpg', 'Juegos Olímpicos', NOW(), 16, 0, 6, 'Preparativos para los Juegos Olímpicos', 'El equipo nacional ha comenzado su preparación para los próximos Juegos Olímpicos. Los atletas están entrenando arduamente y mostrando un gran compromiso para representar a su país en la competencia internacional más importante. Los deportistas están decididos a alcanzar su máximo rendimiento y llevar a casa medallas para su nación. Esta etapa de preparativos es crucial y genera una gran expectativa en los aficionados y seguidores del deporte.') ,
    (2, 'https://...jpg', 'Descubren nueva especie de dinosaurio', NOW(), 18, 0, 3, 'Fascinante hallazgo!', 'Científicos han anunciado el descubrimiento de una nueva especie de dinosaurio, que ha sido denominada "Diplodocus magnificus". Los fósiles encontrados revelan características únicas de esta criatura prehistórica, brindando nuevas perspectivas sobre la evolución y la diversidad de los dinosaurios. Este hallazgo emocionante proporciona información valiosa para comprender mejor el pasado de nuestro planeta.'),
    (3, 'https://...jpg', 'Estudio revela los beneficios de la meditación', '2022-06-16 00:23:10', 16, 0, 9, 'Descubrimientos sobre la meditación y su efecto en dla Salud y Bienestar.', 'Un estudio reciente ha demostrado los numerosos beneficios de la meditación para la salud y el bienestar. Los investigadores encontraron que la práctica regular de la meditación puede reducir el estrés, mejorar la concentración y promover un estado de calma mental. Además, se observaron efectos positivos en la salud física, como la disminución de la presión arterial y la mejora del sistema inmunológico. Estos resultados respaldan la importancia de incorporar la meditación en la rutina diaria para mantener un equilibrio integral.'),
    (4, 'https://...jpg', 'Lanzamiento de nuevo álbum de música!', NOW(), 22, 0, 7, 'The show must go on!', 'El aclamado artista ha lanzado su nuevo álbum, que ha generado gran expectativa entre sus seguidores. Con canciones que exploran diversos géneros musicales y letras profundas, este trabajo promete cautivar a los amantes de la música. El artista ha compartido que este álbum representa una nueva etapa en su carrera y refleja su evolución artística. Los fanáticos están ansiosos por disfrutar de estas nuevas composiciones y descubrir las sorpresas que les esperan.'),
    (1, 'https://...jpg', 'Investigadores descubren posible cura para una enfermedad', NOW(), 25, 4, 2, 'Avances médicos en Suiza', 'Un grupo de investigadores ha anunciado un importante avance en la búsqueda de una cura para una enfermedad hasta ahora incurable. Mediante innovadoras terapias génicas, los científicos han logrado revertir los efectos de esta enfermedad en modelos de laboratorio, abriendo nuevas posibilidades para su tratamiento en humanos. Este descubrimiento ofrece esperanza a los pacientes y destaca el potencial de la medicina genética en el combate contra enfermedades difíciles de tratar.'),
    (2, 'https://...jpg', 'Atletas de élite', NOW(), 19, 0, 6, 'Evento deportivo internacional reúne a super deportistas', 'Un evento deportivo de renombre internacional está en marcha, convocando a los mejores atletas de todo el mundo. En esta competencia de alto nivel, los deportistas están demostrando su destreza y habilidades en disciplinas variadas, desde natación y atletismo hasta gimnasia y tenis. Los fanáticos del deporte están siguiendo de cerca las emocionantes actuaciones y disfrutando de un espectáculo deportivo de primer nivel.'),
    (3, 'https://...jpg', 'Nuevas tecnologías revolucionan la industria automotriz', NOW(), 21, 0, 4, 'Avances tecnologicos muy interesates', 'La industria automotriz está experimentando una revolución gracias a las nuevas tecnologías. Desde vehículos eléctricos hasta sistemas de conducción autónoma, los avances están transformando la forma en que nos desplazamos. Estas innovaciones no solo tienen el potencial de reducir la huella ambiental, sino también de mejorar la seguridad vial y la experiencia de conducción. Los fabricantes de automóviles están trabajando arduamente para implementar estas tecnologías y dar forma al futuro del transporte.'),
    (4, 'https://...jpg', 'Exposición de arte contemporáneo destaca talento local', NOW(), 17, 0, 1, 'Evento artístico', 'Una destacada exposición de arte contemporáneo está presentando obras de talentosos artistas locales. Esta muestra diversa y creativa representa una amplia gama de estilos y expresiones artísticas. Los visitantes tienen la oportunidad de apreciar el arte en todas sus formas, desde pinturas y esculturas hasta instalaciones y arte digital. Este evento cultural destaca la importancia del arte en nuestra sociedad y celebra el talento de los artistas de la región.') ,
	(2, 'https://...jpg', 'Descubrimiento arqueológico revela antiguas civilizaciones', NOW(), 23, 0, 1, 'Hallazgo arqueológico asombroso', 'Arqueólogos han hecho un emocionante descubrimiento en una remota región, revelando evidencias de antiguas civilizaciones que existieron hace miles de años. Los hallazgos incluyen ruinas, artefactos y pinturas rupestres que ofrecen nuevas perspectivas sobre la historia y la cultura de estos pueblos perdidos. Este descubrimiento arqueológico es un hito importante en la comprensión de nuestro pasado y despierta el interés de investigadores de todo el mundo.'),
	(3, 'https://...jpg', 'Nueva terapia prometedora para enfermedades neurodegenerativas', NOW(), 26, 0, 2, 'Avances médicos en neurología', 'Científicos han desarrollado una terapia experimental que muestra resultados prometedores en el tratamiento de enfermedades neurodegenerativas, como el Alzheimer y el Parkinson. Esta terapia utiliza enfoques innovadores para estimular la regeneración neuronal y proteger las células cerebrales del daño. Los estudios preclínicos han demostrado una mejoría significativa en los síntomas y la calidad de vida de los pacientes. Este avance representa una luz de esperanza en la lucha contra estas enfermedades debilitantes.'),
	(4, 'https://...jpg', 'Festival de música internacional atrae a multitudes', NOW(), 18, 0, 7, 'Gran evento musical', 'El festival de música más esperado del año está en pleno apogeo, atrayendo a multitudes de amantes de la música de todas partes. Con un cartel de artistas de renombre mundial y una atmósfera vibrante, este evento se ha convertido en un ícono de la escena musical internacional. Los asistentes están disfrutando de actuaciones en vivo inolvidables y compartiendo experiencias musicales únicas. Este festival es una celebración de la diversidad musical y un escaparate para talentos emergentes.'),
	(1, 'https://...jpg', 'Avances en la lucha contra el cambio climático', NOW(), 24, 5, 3, 'Iniciativas para combatir el cambio climático', 'El mundo está tomando medidas concretas para combatir el cambio climático y reducir las emisiones de gases de efecto invernadero. Desde acuerdos internacionales hasta inversiones en energías renovables y proyectos de conservación, se están implementando estrategias para mitigar los impactos del calentamiento global. Estos esfuerzos reflejan la creciente conciencia sobre la importancia de proteger nuestro planeta y garantizar un futuro sostenible para las generaciones venideras.'),
	(2, 'https://...jpg', 'Récord mundial en competencia deportiva', '2022-06-16 00:23:10', 19, 0, 6, 'Logro histórico en el deporte', 'Un atleta ha logrado establecer un nuevo récord mundial en una competencia deportiva de alto nivel. Con una actuación sobresaliente y una dedicación excepcional, ha superado las marcas anteriores y dejado una huella imborrable en la historia del deporte. Este logro destaca la importancia del entrenamiento, la perseverancia y el espíritu competitivo en la búsqueda de la excelencia.'),
	(3, 'https://...jpg', 'Descubrimiento en el espacio revela secretos del universo', '2022-06-16 00:23:10', 27, 0, 4, 'Asombroso descubrimiento astronómico', 'Astrónomos han realizado un descubrimiento sorprendente que arroja luz sobre los misterios del universo. Mediante el uso de telescopios avanzados, han identificado nuevas galaxias distantes y estudiado fenómenos cósmicos extraordinarios. Estos hallazgos ayudan a expandir nuestro conocimiento sobre el cosmos y plantean nuevas preguntas sobre la naturaleza del universo.'),
	(4, 'https://...jpg', 'Premios reconocen el talento en la industria del cine', NOW(), 20, 0, 7, 'Gala de premios cinematográficos', 'La industria del cine ha celebrado una gala de premios en la que se reconoció el talento y la excelencia en el séptimo arte. Actores, directores, guionistas y otros profesionales del cine fueron honrados por sus contribuciones sobresalientes. Esta ceremonia resalta la importancia del cine como forma de expresión artística y celebra los logros de los cineastas de todo el mundo.'),
	(1, 'https://...jpg', 'Nuevas investigaciones arrojan luz sobre la historia antigua', NOW(), 23, 13, 1, 'Descubrimientos históricos fascinantes', 'Investigadores han realizado descubrimientos arqueológicos que ofrecen nuevas perspectivas sobre la historia antigua. Ruinas, artefactos y textos recién descubiertos han revelado detalles intrigantes sobre civilizaciones olvidadas y eventos históricos significativos. Estos hallazgos arrojan luz sobre nuestro pasado y nos ayudan a comprender mejor el desarrollo de la humanidad.'),
	(2, 'https://...jpg', 'Estudio científico desafía teoría aceptada', '2022-06-16 00:23:10', 17, 0, 4, 'Investigación controvertida', 'Un estudio científico reciente ha desafiado una teoría ampliamente aceptada en el campo de la ciencia. Los resultados de esta investigación cuestionan las ideas establecidas y plantean nuevas hipótesis sobre el funcionamiento de fenómenos naturales. Esta controversia científica genera debates y estimula la investigación adicional para explorar y comprender mejor el mundo que nos rodea.'),
	(3, 'https://...jpg', 'Nuevas terapias prometedoras para el tratamiento del cáncer', NOW(), 25, 0, 2, 'Avances médicos en oncología', 'Investigadores han desarrollado terapias innovadoras que muestran promesa en el tratamiento del cáncer. Estas terapias incluyen enfoques como la inmunoterapia, la terapia génica y la medicina de precisión, y ofrecen nuevas esperanzas a los pacientes con cáncer. Los estudios clínicos preliminares han demostrado resultados alentadores y han abierto nuevas puertas para combatir esta enfermedad devastadora.'),
	(4, 'https://...jpg', 'Artista emergente sorprende con su talento', '2022-06-16 00:23:10', 18, 1, 7, 'Descubrimiento en el mundo del arte', 'Un artista emergente ha llamado la atención del mundo del arte con su talento y originalidad. Sus obras expresivas y únicas han cautivado a críticos y amantes del arte, y se han convertido en objeto de admiración y colección. Este artista representa una nueva voz en el panorama artístico y promete seguir sorprendiendo con su creatividad.'),
	(1, 'https://...jpg', 'Avances tecnológicos revolucionan la industria de la moda', NOW(), 22, 0, 5, 'Moda del futuro', 'La industria de la moda está experimentando una transformación gracias a los avances tecnológicos. La integración de la inteligencia artificial, la realidad aumentada y los textiles inteligentes está cambiando la forma en que diseñamos, fabricamos y experimentamos la moda. Estas innovaciones prometen mejorar la sostenibilidad, la personalización y la accesibilidad en el mundo de la moda.'),
	(2, 'https://...jpg', 'Descubrimiento arqueológico revela civilización perdida', '2022-06-16 00:23:10', 26, 0, 1, 'Hallazgo arqueológico extraordinario', 'Arqueólogos han hecho un descubrimiento sin precedentes que revela una civilización perdida en una región remota. Los vestigios arqueológicos encontrados proporcionan información valiosa sobre esta antigua sociedad y su forma de vida. Este hallazgo arqueológico arroja luz sobre la historia humana y abre nuevas perspectivas para investigaciones futuras.'),
	(3, 'https://...jpg', 'Investigadores desarrollan tecnología revolucionaria en energía renovable', '2022-06-16 00:23:10', 24, 0, 4, 'Energía del futuro', 'Un equipo de investigadores ha logrado un avance significativo en el campo de la energía renovable con el desarrollo de una tecnología revolucionaria. Esta innovación permite la generación de energía limpia de manera más eficiente y sostenible, abriendo nuevas posibilidades para reducir nuestra dependencia de los combustibles fósiles y mitigar el cambio climático.'),
	(4, 'https://...jpg', 'Descubrimientos en neurociencia desafían nuestra comprensión del cerebro', NOW(), 20, 0, 2, 'Nuevos hallazgos en neurociencia', 'Investigadores en el campo de la neurociencia han realizado descubrimientos sorprendentes que desafían nuestra comprensión actual del cerebro humano. Estos hallazgos revelan nuevas conexiones neuronales, procesos cognitivos inesperados y mecanismos de plasticidad cerebral. Esta investigación promete expandir nuestro conocimiento sobre el cerebro y tener implicaciones en el tratamiento de enfermedades neurológicas y trastornos mentales.'),
	(1, 'https://...jpg', 'Nuevo estudio demuestra los beneficios del ejercicio regular', NOW(), 18, 0, 9, 'Ejercicio y bienestar', 'Un estudio científico reciente ha confirmado los numerosos beneficios del ejercicio regular para la salud y el bienestar. Se encontró que la actividad física regular no solo mejora la condición física, sino que también reduce el riesgo de enfermedades crónicas, mejora el estado de ánimo y aumenta la longevidad. Estos hallazgos refuerzan la importancia de mantener un estilo de vida activo y saludable.'),
	(2, 'https://...jpg', 'Festival de cine independiente celebra la creatividad y la diversidad', NOW(), 21, 0, 7, 'Celebración del cine independiente', 'Un festival de cine independiente ha reunido a cineastas y amantes del cine para celebrar la creatividad y la diversidad en la industria cinematográfica. Esta plataforma ofrece un espacio para películas independientes y alternativas que exploran nuevos géneros, temas y estilos. El festival destaca el poder del cine como medio de expresión artística y fomenta el diálogo y el intercambio cultural.'),
	(3, 'https://...jpg', 'Investigación revela nuevos datos sobre la evolución humana', NOW(), 26, 10, 4, 'Descubrimiento en paleoantropología', 'Una investigación en el campo de la paleoantropología ha revelado nuevos datos sobre la evolución humana y nuestros antepasados. Mediante el análisis de fósiles y el estudio de ADN antiguo, los científicos han trazado conexiones entre diferentes especies y descubierto características únicas de nuestra historia evolutiva. Estos hallazgos arrojan luz sobre los orígenes y el desarrollo de la humanidad.'),
	(4, 'https://...jpg', 'Nueva empresa de tecnología lanza innovador dispositivo móvil', NOW(), 19, 0, 5, 'Tecnología disruptiva', 'Una nueva empresa de tecnología ha lanzado un dispositivo móvil innovador que promete cambiar la forma en que interactuamos con la tecnología. Con características y capacidades revolucionarias, este dispositivo redefine la experiencia móvil y ofrece nuevas posibilidades en términos de comunicación, entretenimiento y productividad. Esta innovación refleja el constante avance y la evolución de la tecnología móvil.'),
	(1, 'https://...jpg', 'Descubrimientos en astronomía desvelan secretos del universo', '2022-06-16 00:23:10', 23, 0, 4, 'Explorando el cosmos', 'Avances en la astronomía han permitido hacer descubrimientos fascinantes sobre el universo. Nuevos telescopios y observatorios espaciales han revelado fenómenos cósmicos intrigantes, como agujeros negros, planetas extrasolares y señales de vida en otros lugares del universo. Estos hallazgos nos acercan a comprender la vastedad y la complejidad del cosmos.'),
	(2, 'https://...jpg', 'Nuevas investigaciones en medicina prometen tratamientos más efectivos', NOW(), 27, 0, 2, 'Avances médicos prometedores', 'La investigación médica está abriendo nuevas vías para el tratamiento de enfermedades y condiciones médicas. Desde terapias génicas hasta medicina regenerativa y nanomedicina, los avances en medicina prometen tratamientos más efectivos y personalizados. Estos descubrimientos tienen el potencial de mejorar la calidad de vida de millones de personas en todo el mundo.'),
	(3, 'https://...jpg', 'Avances en inteligencia artificial revolucionan diferentes industrias', NOW(), 25, 0, 5, 'La era de la inteligencia artificial', 'La inteligencia artificial está transformando diferentes sectores industriales, desde la atención médica y la automoción hasta el comercio electrónico y la seguridad. Los algoritmos inteligentes y el aprendizaje automático están impulsando la eficiencia, la personalización y la automatización en múltiples procesos. Estos avances tienen el potencial de cambiar la forma en que vivimos y trabajamos.'),
	(4, 'https://...jpg', 'Artista contemporáneo desafía las convenciones del arte', NOW(), 21, 0, 7, 'Rompiendo barreras artísticas', 'Un artista contemporáneo está desafiando las convenciones del arte con su enfoque innovador y provocador. Sus obras despiertan controversia y cuestionan las normas establecidas, llevando el arte a nuevos territorios emocionales y conceptuales. Este artista desafía las barreras y nos invita a reflexionar sobre el significado y el propósito del arte en la sociedad actual.'),
	(1, 'https://...jpg', 'Nuevo descubrimiento arqueológico en Egipto', '2022-06-16 00:23:10', 20, 0, 1, 'Hallazgo asombroso en la categoría de Actualidad', 'Arqueólogos han realizado un descubrimiento emocionante en Egipto, desenterrando una antigua tumba que data de miles de años atrás. El hallazgo revela valiosos artefactos y pinturas murales que proporcionan información fascinante sobre la historia y la cultura de la civilización antigua. Este descubrimiento arqueológico ha generado gran entusiasmo en la comunidad científica y promete arrojar nueva luz sobre el pasado de esta región.'),
	(1, 'https://...jpg', 'Avances en la investigación del cáncer', NOW(), 20, 0, 2, 'Descubrimientos prometedores en la categoría de Sanidad', 'Científicos han logrado importantes avances en la investigación del cáncer, identificando nuevas terapias y enfoques para combatir esta enfermedad devastadora. Estos hallazgos ofrecen esperanza a los pacientes y sus familias, abriendo la puerta a tratamientos más efectivos y personalizados. La comunidad médica está entusiasmada con estos descubrimientos y trabaja arduamente para traducirlos en opciones de tratamiento viables.'),
	(3, 'https://...jpg', 'Descubrimiento de una nueva especie marina', NOW(), 15, 0, 3, 'Emocionante hallazgo en la categoría de Naturaleza', 'Científicos han anunciado el descubrimiento de una nueva especie marina en las profundidades del océano. Esta criatura desconocida hasta ahora presenta características únicas y representa un importante hallazgo para la biodiversidad marina. Los expertos destacan la importancia de proteger los ecosistemas oceánicos y continuar explorando las profundidades para descubrir nuevas formas de vida.'),
	(2, 'https://...jpg', 'Descubrimiento arqueológico revela antiguas civilizaciones', '2022-06-16 00:23:10', 23, 0, 1, 'Hallazgo arqueológico asombroso', 'Arqueólogos han hecho un emocionante descubrimiento en una remota región, revelando evidencias de antiguas civilizaciones que existieron hace miles de años. Los hallazgos incluyen ruinas, artefactos y pinturas rupestres que ofrecen nuevas perspectivas sobre la historia y la cultura de estos pueblos perdidos. Este descubrimiento arqueológico es un hito importante en la comprensión de nuestro pasado y despierta el interés de investigadores de todo el mundo.'),
	(3, 'https://...jpg', 'Nueva terapia prometedora para enfermedades neurodegenerativas', NOW(), 26, 0, 2, 'Avances médicos en neurología', 'Científicos han desarrollado una terapia experimental que muestra resultados prometedores en el tratamiento de enfermedades neurodegenerativas, como el Alzheimer y el Parkinson. Esta terapia utiliza enfoques innovadores para estimular la regeneración neuronal y proteger las células cerebrales del daño. Los estudios preclínicos han demostrado una mejoría significativa en los síntomas y la calidad de vida de los pacientes. Este avance representa una luz de esperanza en la lucha contra estas enfermedades debilitantes.'),
	(4, 'https://...jpg', 'Festival de música internacional atrae a multitudes', NOW(), 18, 0, 7, 'Gran evento musical', 'El festival de música más esperado del año está en pleno apogeo, atrayendo a multitudes de amantes de la música de todas partes. Con un cartel de artistas de renombre mundial y una atmósfera vibrante, este evento se ha convertido en un ícono de la escena musical internacional. Los asistentes están disfrutando de actuaciones en vivo inolvidables y compartiendo experiencias musicales únicas. Este festival es una celebración de la diversidad musical y un escaparate para talentos emergentes.'),
	(1, 'https://...jpg', 'Avances en la lucha contra el cambio climático', NOW(), 24, 0, 3, 'Iniciativas para combatir el cambio climático', 'El mundo está tomando medidas concretas para combatir el cambio climático y reducir las emisiones de gases de efecto invernadero. Desde acuerdos internacionales hasta inversiones en energías renovables y proyectos de conservación, se están implementando estrategias para mitigar los impactos del calentamiento global. Estos esfuerzos reflejan la creciente conciencia sobre la importancia de proteger nuestro planeta y garantizar un futuro sostenible para las generaciones venideras.'),
	(2, 'https://...jpg', 'Récord mundial en natación', NOW(), 20, 0, 6, 'Logro deportivo impresionante', 'Un nadador talentoso ha establecido un nuevo récord mundial en una competencia internacional de natación. Su destacada actuación y su determinación incansable le han permitido superar marcas anteriores y dejar una huella en la historia del deporte. Este logro es un testimonio del arduo entrenamiento y la dedicación del atleta, así como de su habilidad para superar límites y desafiar las expectativas.'),
	(3, 'https://...jpg', 'Descubren nuevas especies en selva tropical', NOW(), 19, 0, 3, 'Exploración en biodiversidad', 'Una expedición científica en una selva tropical ha descubierto varias especies nuevas para la ciencia, incluyendo plantas, insectos y animales. Estos hallazgos resaltan la importancia de conservar estos ecosistemas ricos en biodiversidad y promueven la investigación y el conocimiento sobre las especies que habitan en ellos. La expedición también ha revelado la existencia de hábitats únicos y frágiles que requieren protección para preservar la vida en la Tierra.'),
    (4, 'https://...jpg', 'Nueva legislación para proteger el medio ambiente', '2022-06-16 00:23:10', 22, 0, 3, 'Compromiso con la sostenibilidad', 'Un nuevo conjunto de leyes ha sido aprobado para fortalecer la protección del medio ambiente y promover la sostenibilidad. Estas regulaciones abordan temas como la reducción de residuos, la conservación de los recursos naturales y la promoción de prácticas ambientalmente responsables en los sectores público y privado. Esta legislación marca un paso importante hacia un futuro más verde y respetuoso con el planeta.'),
	(2, 'https://...jpg', 'Descubren nueva especie de mariposa en selva amazónica', NOW(), 17, 0, 3, 'Maravillas de la naturaleza', 'Científicos han identificado una nueva especie de mariposa en la selva amazónica. Esta colorida mariposa posee patrones únicos en sus alas y ha sido catalogada como una especie endémica de la región. El descubrimiento destaca la importancia de preservar los ecosistemas naturales y la biodiversidad que albergan. Estos hallazgos ofrecen nuevas oportunidades para estudiar y comprender mejor la vida en la selva tropical.'),
	(3, 'https://...jpg', 'Inauguración de nuevo hospital regional', '2022-06-16 00:23:10', 25, 0, 2, 'Mejora en infraestructura sanitaria', 'Un nuevo hospital regional ha sido inaugurado, brindando servicios de atención médica de calidad a la comunidad. Equipado con tecnología de vanguardia y un equipo médico altamente capacitado, este centro de salud se convierte en un punto de referencia en la región. La apertura del hospital representa un paso importante hacia la mejora de la infraestructura sanitaria y el acceso a la atención médica en la zona.'),
	(1, 'https://...jpg', 'Estudio revela beneficios para la salud de estar en contacto con la naturaleza', '2022-06-16 00:23:10', 28, 0, 3, 'Bienestar y naturaleza', 'Una investigación científica ha demostrado los numerosos beneficios que tiene pasar tiempo en la naturaleza para nuestra salud y bienestar. Estar en contacto con entornos naturales, como bosques o parques, se ha asociado con una reducción del estrés, mejora del estado de ánimo, aumento de la vitalidad y fortalecimiento del sistema inmunológico. Estos hallazgos subrayan la importancia de conectarnos con la naturaleza y fomentar un estilo de vida equilibrado.'),
	(2, 'https://...jpg', 'Nuevo tratamiento prometedor contra enfermedades cardiovasculares', '2022-06-16 00:23:10', 21, 0, 2, 'Avances en cardiología', 'Investigadores han desarrollado un nuevo tratamiento que muestra resultados prometedores en el manejo de enfermedades cardiovasculares, como la hipertensión y la enfermedad coronaria. Este enfoque terapéutico innovador utiliza tecnología de vanguardia para mejorar la función cardíaca y reducir los riesgos asociados con estas enfermedades. Estos avances médicos ofrecen esperanza para aquellos que sufren de afecciones cardíacas y pueden tener un impacto significativo en la salud cardiovascular de la población.'),
	(4, 'https://...jpg', 'Descubren nueva reserva natural en área protegida', '2022-06-16 00:23:10', 18, 0, 3, 'Conservación de hábitats', 'Se ha descubierto una nueva reserva natural dentro de un área protegida, ampliando la extensión de hábitats preservados para diversas especies. Esta adición fortalece los esfuerzos de conservación y brinda más oportunidades para la investigación científica y el turismo ecológico. El descubrimiento destaca la importancia de proteger y preservar los ecosistemas naturales para garantizar la supervivencia de la vida silvestre y mantener la biodiversidad.'),
    (1, 'https://...jpg', 'Crece el comercio electrónico en el mercado global', NOW(), 26, 0, 5, 'Transformación en los hábitos de consumo', 'El comercio electrónico continúa experimentando un crecimiento significativo en el mercado global. Cada vez más personas optan por realizar compras en línea debido a la comodidad, la variedad de productos y los precios competitivos. Este cambio en los hábitos de consumo está transformando la forma en que las empresas operan y se espera que el comercio electrónico siga en aumento en los próximos años.'),
	(2, 'https://...jpg', 'Nuevas regulaciones fiscales para incentivar la inversión', NOW(), 19, 0, 5, 'Estímulo a la inversión empresarial', 'Se han implementado nuevas regulaciones fiscales con el objetivo de fomentar la inversión y el crecimiento económico. Estas medidas incluyen reducciones de impuestos para las empresas, incentivos para la inversión en sectores estratégicos y la simplificación de trámites administrativos. Las autoridades buscan crear un entorno propicio para los negocios y estimular la actividad empresarial.'),
	(3, 'https://...jpg', 'Emprendedores exitosos comparten sus experiencias', NOW(), 23, 0, 5, 'Inspiración y consejos para emprendedores', 'Destacados emprendedores han compartido sus historias de éxito y brindado consejos a aquellos que desean iniciar su propio negocio. Estas experiencias ofrecen inspiración y conocimientos prácticos sobre diversos aspectos del emprendimiento, como la planificación, la financiación, la gestión de equipos y la superación de desafíos. Las lecciones aprendidas por estos emprendedores pueden ser valiosas para quienes están en el inicio de su camino empresarial.'),
	(4, 'https://...jpg', 'Crecimiento del mercado de criptomonedas', NOW(), 27, 0, 5, 'Auge de las criptomonedas', 'El mercado de criptomonedas continúa experimentando un crecimiento significativo. El interés en las criptodivisas, como Bitcoin y Ethereum, ha aumentado tanto entre inversores institucionales como individuales. Este crecimiento ha llevado a una mayor aceptación y adopción de las criptomonedas como una forma legítima de inversión y medio de intercambio. Sin embargo, también plantea desafíos regulatorios y de seguridad que deben abordarse.'),
	(2, 'https://...jpg', 'Nueva empresa tecnológica recibe financiamiento millonario', '2022-06-16 00:23:10', 21, 0, 5, 'Impulso a la innovación tecnológica', 'Una empresa emergente en el sector tecnológico ha obtenido una importante financiación de capital de riesgo. Esta inversión millonaria respalda el desarrollo de nuevas tecnologías y soluciones innovadoras en áreas como inteligencia artificial, blockchain y energías renovables. El éxito de esta empresa refuerza la importancia de la innovación y el papel de la tecnología en la economía actual.'),
	(3, 'https://...jpg', 'Informe económico pronostica crecimiento sostenido','2022-06-16 00:23:10', 24, 0, 5, 'Perspectivas positivas para la economía', 'Un informe económico reciente ha pronosticado un crecimiento sostenido en la economía global. Se prevé un aumento en la demanda de bienes y servicios, así como una mejora en las condiciones del mercado laboral. Estas perspectivas positivas son alentadoras para empresas y consumidores, ya que indican un mayor dinamismo en la actividad económica y oportunidades de crecimiento.');
SELECT * FROM users;
SELECT * FROM news;
SELECT * FROM category;

SELECT * FROM news WHERE userId = 4;

