CREATE DATABASE IF NOT EXISTS hb_news;
USE hb_news;

DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
    surname VARCHAR(200),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(512) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    imageUrl VARCHAR(512),
    biography VARCHAR(250),
    lastUpdatedAt DATETIME NULL,
    registrationcode BIGINT UNIQUE,
    active BOOLEAN NOT NULL DEFAULT false,
    isadmin BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE category (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100)
);

CREATE TABLE news (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userId INT UNSIGNED NOT NULL,
    imagenUrl VARCHAR(512),
    title VARCHAR(250) NOT NULL,
    publishDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false,
    score INT NOT NULL DEFAULT 0,
    fakeNew INT NOT NULL DEFAULT 0,
    categoryId INT UNSIGNED NOT NULL,
    introText VARCHAR(512) NOT NULL,
    text TEXT,
    FOREIGN KEY (userId) REFERENCES users(id)  ON DELETE CASCADE,
    FOREIGN KEY (categoryId) REFERENCES category(id)
);

